### ISSUE TITLE
install idea gherkin plugin not support feature file jump step to golang file?

### ISSUE THREAD

**Issue by baisijian** [cucumber/gherkin#112]
### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by mpkorstanje** [comment]
You should probably ask JetBrains. https://youtrack.jetbrains.com/
