### ISSUE TITLE
How to print a GherkinDocument to text with pretty format

### ISSUE THREAD

**Issue by Milk-Tang** [cucumber/gherkin#118]
Since I have a GherkinDocument, I wonder how to write it into a file with a pretty format?

**Comment by jenisys** [comment]
Do you mean:

* With syntax coloring ?
* With uniform formatting, like indented with 2 spaces (or: 4 spaces) ?

REGARDING: Syntax coloring / highlighting

* Use `gherkin` as language/syntax-marker, like:

```gherkin
# — FILE: features/example.feature
Feature: Example 1
  Scenario: S1
    Given a step passes
   When another step passes
```

**Comment by Milk-Tang** [comment]
> 
`gherkinDocument, err := gherkin.ParseGherkinDocument(reader)`
There I got a instance of  `GherkinDocument` by method `gherkin.ParseGherkinDocument`,
and if I create a GherkinDocument instance by myself but not `ParseGherkinDocument`,
how can I write it to a ".feature" file in my code?
And here the struct of GherkinDocument :
`type GherkinDocument struct {
	Uri      string     `json:"uri,omitempty"`
	Feature  *Feature   `json:"feature,omitempty"`
	Comments []*Comment `json:"comments"`
}`

**Comment by jenisys** [comment]
SEE: [cucumber.gherkin-Utility issue 4](https://github.com/cucumber/gherkin-utils/issues/4)

**Comment by Milk-Tang** [comment]
thanks
