### ISSUE TITLE
Gherkin releases on pypi

### ISSUE THREAD

**Issue by tra-github** [cucumber/gherkin#119]
Hi,
I notice gherkin on pypi is still version 24.1.0. Are latest versions no longer released on pypi?
Sylvie

**Comment by mpkorstanje** [comment]
No. Not at this moment.

- There aren't enough drive by contributors to help keep us up to date with Pythons state of the art. 
- The Cucumber Project currently permanent maintainers (see https://mattwynne.net/new-beginning).

Duplicate of #40.
