### ISSUE TITLE
Support asterisk as a conjuction

### ISSUE THREAD

**Issue by qi55wyqu** [cucumber/gherkin#123]
The gherkin syntax supports using an asterisk instead of `And` ([https://cucumber.io/docs/gherkin/reference/](https://cucumber.io/docs/gherkin/reference/)).

When I use `And`, the step is parsed as `'keyword': 'And ', 'keywordType': 'Conjunction'`.

However when I use `*` the step is parsed as `'keyword': '* ', 'keywordType': 'Unknown'`.

It would be great if the correct keywordType was set.

**Comment by elchupanebrej** [comment]
`*` means that it could be used by any keyword step
`And` means that type of step is substituted from the previous step

So they have different meanings

**Comment by qi55wyqu** [comment]
Ah that makes sense, thank you! I think this issue can be closed then.

This difference isn't clear from the official documentation though.
