### ISSUE TITLE
Add support for python 3.11

### ISSUE THREAD

**Issue by qi55wyqu** [cucumber/gherkin#125]
Python 3.11 does not seem to be supported yet.

Python 3.10 shows a warning `DeprecationWarning: 'U' mode is deprecated`.

Running `gherkin.parser.Parser().parse("test.feature")` under Python 3.11 results in a `ValueError`

Output of pytest:
```
.../virtualenvs/.../lib/python3.11/site-packages/gherkin/parser.py:63: in parse
    token_scanner = TokenScanner(token_scanner_or_str) if isinstance(token_scanner_or_str, str) else token_scanner_or_str
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <gherkin.token_scanner.TokenScanner object at 0x7fa4bccfbe90>
path_or_str = '.../unittests/test.feature'

    def __init__(self, path_or_str):
        if os.path.exists(path_or_str):
>           self.io = io.open(path_or_str, 'rU', encoding='utf8')
E           ValueError: invalid mode: 'rU'
```
Environment:
- Python 3.11.4
- gherkin-official 24.1.0
- (pytest 7.4.0)

It would be great if you could add support for Python 3.11. Thank you very much.

**Comment by yurabysaha** [comment]
@mpkorstanje This is still a problem, also I can see pip pin to the old repo and it always gherkin-official 24.1.0 is it possible to fix it too?

**Comment by mpkorstanje** [comment]
Cucumber is an opensource project, currently mostly run by mostly unpaid volunteers. We do not have a dedicated python maintainer and the other maintainers are somewhat lacking in either python knowledge, time and/or motivation to look at this.

If you or any one else would benefit from this and would be willing to do the work, [please hop onto Slack](https://github.com/cucumber#get-in-touch-%EF%B8%8F), `#commiters` channel.
