### ISSUE TITLE
Compiler for Objective-C

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin#130]
Work to do:
- [ ] Update `Makefile` to generate pickles
- [ ] Port the compiler from one of the other languages

Then we should be ready for a Cucumber iOS and Cucumber OSX based on [microcuke](https://github.com/cucumber/microcuke)

@LiohAu - interested?

**Comment by aslakhellesoy** [comment]
@Ahmed-Ali maybe you're interested in this?

**Comment by Ahmed-Ali** [comment]
@aslakhellesoy if I understood it correctly, then it looks really close to [Cucumberish](https://github.com/Ahmed-Ali/Cucumberish/)!
