### ISSUE TITLE
Support alternative Objective-C build process

### ISSUE THREAD

**Issue by moreau-nicolas** [cucumber/gherkin#137]
The current Objective-C build process uses Xcode, which is not available on Linux. I suggest moving to a more platform-independant alternative, such as gcc-objc.

At the moment a fresh `git clone` of the project cannot compile on a Linux box (or even a Windows one).

**Comment by aslakhellesoy** [comment]
Yeah requiring xcode is obviously not ideal. Would you be interested in sending a PR to address this?

**Comment by moreau-nicolas** [comment]
I'm willing, but I'm not sure I'm the best person to do this:  I don't have access to an Apple computer and have no experience at all with Objective-C.

**Comment by aslakhellesoy** [comment]
Isn't the point of this bug to make the build pass on a non-apple computer (Linux and/or Windows)?

**Comment by moreau-nicolas** [comment]
Of course it is! My feeling of not-being-the-best-guy-for-the-job is more related to my lack of knowledge on Objective-C than lack of a computer.
I'll try and propose something.

**Comment by aslakhellesoy** [comment]
I don't know Objective-C either, and I don't think you need to know any in order to compile it ;-)

**Comment by moreau-nicolas** [comment]
I just tried to (naively) compile all \*.m files into object files with gcc 4.8 but it does **not** work.
Clang 3.4 does not work either.
Both don't seem to support \*.pch files, so I tried manually importing <Foundation/Foundation.h> at the very beginning of each \*.m file, but no dice, it still is not enough.

I got the following error, which seems pretty obscure to me:
```
GHTag.m:15:13: error: synthesized property 'location' must either be named the same as a compatible instance variable or must
      explicitly name an instance variable
@synthesize location;
            ^
GHTag.m:16:13: error: synthesized property 'name' must either be named the same as a compatible instance variable or must explicitly
      name an instance variable
@synthesize name;
            ^
2 errors generated.
```

Here is the command that generated this error:
```
cd objective-c/Gherkin
clang -ObjC -I/usr/include/GNUstep -c GHTag.m
```

Maybe @LiohAu could help?
