### ISSUE TITLE
Keep original keywords when feature file is parsed (js)

### ISSUE THREAD

**Issue by amiceli** [cucumber/gherkin#143]
### 🤔 What's the problem you're trying to solve?

I'm using `@cucumber/messages` and `@cucumber/gherkin` in a project in my comparny.
We are building a tool for us who need to convert feature file to json.

Parsing to JSON is OK but we need to keep original keywords like And, When, Then who are translated to Action, Action etc.

### ✨ What's your proposed solution?

Currently I don't know if it's possible to customize parser for keyword.
I read README.md many times but it's hard to understand. 

### ⛏ Have you considered any alternatives or workarounds?

Currently I don't found a workaround.

### 📚 Any additional context?

A example of feature file content with keywords we use : 

~~~feature
Feature: Awesome feature

    Scenario: ...
        Given ...
        When ...
        And ...
        Then ...
~~~

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by amiceli** [comment]
Maybe I'm confused ^^. 
This is my JS script : 

~~~js
const fs = require('fs/promises')
const Gherkin = require('@cucumber/gherkin')
const Messages = require('@cucumber/messages')

async function main() {
    const content = await fs.readFile('./index.feature')

    const uuidFn = Messages.IdGenerator.uuid()
    const builder = new Gherkin.AstBuilder(uuidFn)
    const matcher = new Gherkin.GherkinClassicTokenMatcher() // or Gherkin.GherkinInMarkdownTokenMatcher()

    const parser = new Gherkin.Parser(builder, matcher)
    const gherkinDocument = parser.parse(content.toString())
    const pickles = Gherkin.compile(gherkinDocument, './index.feature', uuidFn)

    const json = JSON.stringify(pickles)

    await fs.writeFile('./index.json', json)
}

main().then(() => {
    console.debug('ok')
})
~~~

After I run it, `index.json` file is generated. For example it contains : 

~~~json
{
    "id": "7d6c07bd-6618-4602-9222-ad3806f7aaf3",
    "text": "...",
    "type": "Action",
    "astNodeIds": [
        "ac60a9e6-3a7c-478c-92fa-23ac83e79acd"
    ]
}
~~~

And is it possible to have `When`, `And`, `When` etc instead of `Action`, `Outcome` etc ?

**Comment by mpkorstanje** [comment]
You're looking at the JSON for the Pickles. Not the Gherkin document.

The purpose of the Pickles is explained here: https://github.com/cucumber/gherkin#pickles

But you'll want to look at the Gherkin document.

**Comment by amiceli** [comment]
Thanks for your help.
