### ISSUE TITLE
new ruby gem release

### ISSUE THREAD

**Issue by akostadinov** [cucumber/gherkin#147]
Hello, could somebody perform a new ruby gem release after #146 and #114? At the moment fixes/changes are hard to use due to lack of new gem in the central.

**Comment by aslakhellesoy** [comment]
I'll see what I can do...

**Comment by aslakhellesoy** [comment]
Done! 3.2.0 is released.

Please note - the gem name and module name changed from gherkin3 to gherkin! In retrospect I realise we should have released 4.0.0 in order to stick with Semver. Sorry!

**Comment by akostadinov** [comment]
@aslakhellesoy, I don't think this resolves the immediate issue because cucumber 2.2.0 /latest/ does still require `gherkin3` artifact. So now we need a new `cucumber` release using correct gem name and module name.

**Comment by aslakhellesoy** [comment]
Fancy sending a PR for that?
