### ISSUE TITLE
Expansion on CONTRIBUTING.md

### ISSUE THREAD

**Issue by merrua** [cucumber/gherkin#150]
This might just be me, who hasn't used make much, but the building instructions in CONTRIBUTING.md could probably be expanded on.

Like for a new machine, freshly set to a base OS how long does it take to do the setup? 
Is there any gottchas in the installation order? 
For a virtual machine how much space does it take up (good for someone with an older model machine too)

I was looking to do the setup to build and run the tests, but its hard to start it when you don't know how much time you have to put in to get there and aren't used to the full stack.

**Comment by aslakhellesoy** [comment]
How long it takes to set something up depends on how fast your machine is, what OS you're on, how fast your network is and how skilled you are. 

It will vary between 10 minutes and 10 days.
