### ISSUE TITLE
UndefinedConversionError

### ISSUE THREAD

**Issue by westlakem** [cucumber/gherkin#151]
I've updated cucumber from 2.0.2 and now it's using Gherkin3.  As soon as I tried to start the launcher I get the following issue:

Encoding::UndefinedConversionError: "\x81" to UTF-8 in conversion from Windows-1
252 to UTF-8
             encode at org/jruby/RubyString.java:5210
         initialize at json/ext/Parser.java:175
                new at json/ext/Parser.java:151
              parse at C:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/json-1.8.3-jav
a/lib/json/common.rb:155
  <module:Gherkin3> at C:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/gherkin3-3.1.2
/lib/gherkin3/dialect.rb:5
              <top> at C:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/gherkin3-3.1.2
/lib/gherkin3/dialect.rb:3
            require at org/jruby/RubyKernel.java:939
            require at C:/jruby-9.0.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel
_require.rb:54
             (root) at uri:classloader:/jruby/kernel/kernel.rb:1
              <top> at uri:classloader:/jruby/kernel/kernel.rb:13
            require at org/jruby/RubyKernel.java:939
            require at C:/jruby-9.0.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel
_require.rb:54
             (root) at C:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/gherkin3-3.1.2
/lib/gherkin3/token_matcher.rb:1
              <top> at uri:classloader:/jruby/kernel/kernel.rb:1
            require at org/jruby/RubyKernel.java:939
            require at C:/jruby-9.0.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel
_require.rb:54
              <top> at uri:classloader:/jruby/kernel/kernel.rb:13
            require at org/jruby/RubyKernel.java:939
            require at C:/jruby-9.0.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel
_require.rb:54
              <top> at C:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/gherkin3-3.1.2
/lib/gherkin3/parser.rb:3
            require at org/jruby/RubyKernel.java:939
            require at C:/jruby-9.0.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel
_require.rb:54
              <top> at C:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/cucumber-core-
1.3.1/lib/cucumber/core/gherkin/parser.rb:1
            require at org/jruby/RubyKernel.java:939
            require at C:/jruby-9.0.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel
_require.rb:54
              <top> at C:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/cucumber-core-
1.3.1/lib/cucumber/core/gherkin/parser.rb:1
            require at org/jruby/RubyKernel.java:939
            require at C:/jruby-9.0.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel
_require.rb:54
              <top> at C:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/cucumber-core-
1.3.1/lib/cucumber/core.rb:1
            require at org/jruby/RubyKernel.java:939
             (root) at C:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/cucumber-core-
1.3.1/lib/cucumber/core.rb:1

Any help would be greatly appreciated

**Comment by aslakhellesoy** [comment]
What Java/JRuby/Cucumber versions are you using and how can we reproduce this?

**Comment by aslakhellesoy** [comment]
Is your feature file saved with UTF-8 encoding? It sounds like you're using a different encoding.

**Comment by westlakem** [comment]
@aslakhellesoy 

OK I've found the root cause and steps to reproduce.

#1 I have a cucumber test suite

#2 Download pstools from https://technet.microsoft.com/en-us/sysinternals/pstools.aspx

#3 using psexec try to execute cucumber on a remote machine 
   IE: \path\to\pstools psexec \\remoteMachine cmd
      (should open up a command prompt on the remote machine)
      then " cd path\to\cucumber_project & cucumber"

#4 You should see the error above.


ADDITIONAL DETAILS:

This only happens when you're trying to do this remotely (tried through psexec & Windows PowerShell remote)

The error occurs at line:5 of lib\gherkin3\dialect.rb:

       DIALECTS = JSON.parse File.read(DIALECT_FILE_PATH)

When it tries to parse  lib\gherkin3\gherkin-languages.json

**Comment by aslakhellesoy** [comment]
Please try to reproduce it in a different way. 

Make sure you have git and jruby on the remote machine. Then try this:

```
git clone https://github.com/cucumber/gherkin-ruby.git
cd gherkin-ruby
jgem install bundler
jruby -S bundle exec rspec
```

What output do you get?

**Comment by westlakem** [comment]
Ok so after going down a lot of rabbit holes and getting nowhere I finally found the solution.  There's a file encoding switch on Java that defaulted to windows1252 format.  After changing the encoding to UTF8 the issue went away.  To anyone else who may come across this issue you can check if this is the issue by running


```
irb
puts JRuby.runtime.encoding_service.getJavaDefault
puts JRuby.runtime.encoding_service.getLocaleEncoding or 
puts JRuby.runtime.encoding_service.locale_encoding
exit
```
If you find the JavaDefault to be windows 1252 then you can set 
    
    -Dfile.encoding=UTF8

in your JAVA_OPTS env variable and it should fix the issue

**Comment by aslakhellesoy** [comment]
Actually - you found a bug. The parser should work even if the system encoding is not UTF-8. Fix coming shortly.
