### ISSUE TITLE
Consistency in AST node types (Ruby)

### ISSUE THREAD

**Issue by enkessler** [cucumber/gherkin#155]
So, the AST produced by the parser contains a bunch of nodes and they all look something like this:

{:type=>"Tag", :location=>{:line=>1, :column=>1}, :name=>"@a_tag"}, "name"=>"@a_tag", "line"=>1}

I've noticed that some of them have Symbol types (e.g. :Feature, :Scenario, :DataTable) and others have String types (e.g. "Tag", "TableCell", "TableRow"). Is that intentional or is that just how someone happened to code it?

**Comment by aslakhellesoy** [comment]
Sounds like a bug. Should be reproducible with an RSpec spec.

Would love a PR for this.

**Comment by enkessler** [comment]
I'll take a crack at it.

**Comment by enkessler** [comment]
Well, I've managed to add an RSpec test for it but I can't figure out which bit of the code is generating the difference.

**Comment by enkessler** [comment]
Hey! Found them. What a difference lunch makes.

So before I go and change everything to be one way or the other, is the preference to have them all be Symbols or to all be Strings?

**Comment by mattwynne** [comment]
I think they may as well be strings - they're very un-idiomatically named symbols anyway. WDYT @tooky @brasmusson?

**Comment by aslakhellesoy** [comment]
Symbol keys are mire idiomatic than string keys, sonlet's use symbols across the board.

The symbol names are indeed unconventional for ruby, but that's a side-effect of Gherkin's cross-platformness.

I still think symbols are more idiomatic here.

**Comment by aslakhellesoy** [comment]
My point is, the keys are unidiomatic whether we use strings or symbols.

**Comment by mattwynne** [comment]
Yeah and they do repeat, so a symbol makes more sense in this case, you're right.

Symbols it is.

**Comment by aslakhellesoy** [comment]
This is fixed by #158
