### ISSUE TITLE
Cucumber Parsing Issue

### ISSUE THREAD

**Issue by mehwishaziz2025** [cucumber/gherkin#159]
<img width="624" alt="screen shot 2016-02-07 at 12 53 01 pm" src="https://cloud.githubusercontent.com/assets/17104312/12874067/bba1a7b0-cd9a-11e5-9e21-5d98d1c2b0e9.png">

<img width="293" alt="screen shot 2016-02-07 at 12 53 33 pm" src="https://cloud.githubusercontent.com/assets/17104312/12874074/cb929f58-cd9a-11e5-94df-4c3e016b8d71.png">
<img width="637" alt="screen shot 2016-02-07 at 12 55 17 pm" src="https://cloud.githubusercontent.com/assets/17104312/12874078/d2717d12-cd9a-11e5-9a99-448481a17ca7.png">

and my runner file has all:
<img width="264" alt="screen shot 2016-02-07 at 12 53 21 pm" src="https://cloud.githubusercontent.com/assets/17104312/12874128/a93209ac-cd9b-11e5-9777-b2b8b5bd1472.png">

I am getting these bunch of errors. Can someone please help. Thanks-

**Comment by paoloambrosio** [comment]
This is not a support forum: read https://cucumber.io/support

Your question is not related to the Gherkin project but to Cucumber-JVM

Your feature looks wrong: you can read https://cucumber.io/docs/reference
