### ISSUE TITLE
Load Gherkin (javascript) by using UMD fails

### ISSUE THREAD

**Issue by rianby64** [cucumber/gherkin#168]
Hi!
I've a question about how to "require" gherkin module.
Let's consider [the 7th line](https://github.com/cucumber/gherkin/blob/master/javascript/index.js#L7) where gherkin is being exported
```javascript
// package.json says that the module's name is gherkin... not Gherkin 
window.Gherkin = factory();
```

I was playing around with this [UMD Babel tool](http://babeljs.io/docs/plugins/transform-es2015-modules-umd/) and found that UMD Babel names the module as its filename. E.g:

```javascript
// correct.js
export default function myFunction() {
  return 'a text for correct-module';
};
```
Will be translated into
```javascript
// correct.js
(function (global, factory) {
  if (typeof define === "function" && define.amd) {
    define(['exports'], factory);
  } else if (typeof exports !== "undefined") {
    factory(exports);
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports);
    global.correct = mod.exports;  // ----- Here the module's name is the filename
  }
})(this, function (exports) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.default = myFunction;
  function myFunction() {
    return 'a text for correct-module';
  };
});
```

And a PascalCase JS file like this:
```javascript
// Incorrect.js
export default function myFunction() {
  return 'a text for incorrect-module';
};
```
Will result in this:
```javascript
// Incorrect.js (Notice that the filename is PascalCase)
(function (global, factory) {
  if (typeof define === "function" && define.amd) {
    define(['exports'], factory);
  } else if (typeof exports !== "undefined") {
    factory(exports);
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports);
    global.Incorrect = mod.exports;  // ----- Here the module's name is PascalCase too 
  }
})(this, function (exports) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.default = myFunction;
  function myFunction() {
    return 'a text for incorrect-module';
  };
});
```

So! All that introduction I made was to ask:
Can you please help me to "require" from browser the module "gherkin"?

I already found a solution for [index.js](https://github.com/cucumber/gherkin/blob/master/javascript/index.js)

```javascript
// index.js
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define([], factory);
  } else if (typeof window === 'object') {
    // Browser globals (root is window)
    window.Gherkin = factory();
    window.gherkin = window.Gherkin;  //// Can you please add this line?
  } else {
    // Node.js/IO.js
    module.exports = factory();
  }
}(this, function () {
  return {
    Parser: require('./lib/gherkin/parser'),
    TokenScanner: require('./lib/gherkin/token_scanner'),
    TokenMatcher: require('./lib/gherkin/token_matcher'),
    AstBuilder: require('./lib/gherkin/ast_builder'),
    Compiler: require('./lib/gherkin/pickles/compiler')
  };
}));
```

But, why I'm not doing a pull request?
Because I couldn't understand the way you build the module gherkin for Javascript. If you're using a tool to translate gherkin into AMD and CommonJS module or something similar.

And why an additional line I suggest?
I know that the documentation says that you can import by calling the PascalCase for Gherkin.

Let's consider the following case for browser:

```html
...
<script src="bower_copmonets/gherkin/dist/gherkin.js"></script>
<script>
  var parser = new Gherkin.Parser();
  ...
</script>
...
```

If you change the export name, then that code will break.
So, think about it...

Thanks a lot! The Gherkin module changed my life in programming!

**Comment by stof** [comment]
I don't understand the relation between the UMD babel tool used by your own code, and the name of the Global variable used in gherkin for its UMD build. Can you describe what does not work for you ?

**Comment by stof** [comment]
OK, looks like the detection of CommonJS usage is weird in gherkin though, forbidding to use CommonJS in a browser, which would break compatibility with Browserify or other similar building tools.

**Comment by rianby64** [comment]
Yes :smile: When calling Gherkin module through require or import will take as argument the file's name.

So, the given case will not work.
```javascript
// package.json says that the module's name is gherkin... not Gherkin 
window.Gherkin = factory();
```

Oh! you already fixed [it](https://github.com/cucumber/gherkin/blob/master/javascript/index.js#L7)!
```javascript
// Was something like
module.Gherkin = factory();
// But now it seems to be correct
module.exports = factory();
```
I swear! It was hard-coded :smiley: 

I don't have any more questions about this issue. Thanks a lot!

**Comment by stof** [comment]
yeah, the root  is already fixed by https://github.com/cucumber/gherkin/pull/204 already.

so please close this issue (I cannot do it myself, as I'm not a maintainer of gherkin)
