### ISSUE TITLE
Can a ScenarioDefinition really have more than one linked Example?

### ISSUE THREAD

**Issue by pjlsergeant** [cucumber/gherkin#172]
As per the AST diagram, which seems wrong, or is this a new feature?

**Comment by rianby64** [comment]
I couldn't understand the question. May you please write an example?

**Comment by aslakhellesoy** [comment]
@pjlsergeant the AST diagram (and the gherkin.berp grammar) indicate that ScenarioOutline (and not the ScenarioDefinition supertype) can have zero or many Examples. And that's correct.

Why do you think this is wrong?

**Comment by pjlsergeant** [comment]
The AST diagram suggests that an `Examples` node has one header and many rows, suggesting it's essentially a whole table. I am having an imagination failure understanding what you'd do with more than one table with a Scenario Outline?

**Comment by paoloambrosio** [comment]
You should be able to put tags and filter in/out examples.

**Comment by pjlsergeant** [comment]
> You should be able to put tags and filter in/out examples.

To me, that would suggest that one of two things is happening: `Examples` is meant to represent one single example row, or alternatively that all rows from all `Examples` objects that are merged depending on which are selected from tags? Is the former or latter correct?

**Comment by mattwynne** [comment]
People use the tables to group similar examples. "Here are some examples where the account is overdrawn, here are some examples where the card has expired" etc.

Does that make more sense? I'd type a full example but I'm on my phone :) 📱

**Comment by pjlsergeant** [comment]
As it is, the AST suggests the following is valid:

```
Scenario Outline:
   Given '<foo>'
   Examples:
     |foo|
     |bar|
     |ban|
   Examples:
     |foo|
     |baz|
     |moo|
```

Is that correct? If so, are the example tables simply merged?

**Comment by paoloambrosio** [comment]
This is a more complex example with tags, descriptions, etc.

```
  Scenario Outline: Very important stuff

    Given I have a <precondition>
    When I do something
    Then <something else> should happen

    @feature_switch_off
    Examples: Feature switch off

      With the feature disabled, behaviour is different

      | precondition | something else |
      | a1           | b1             |
      | a2           | b2             |

    @requires_other_system @feature_switch_on
    Examples: Feature switch on

      The business paid billions for this feature! New cool stuff!

      | precondition | something else |
      | a1           | b3             |
      | a2           | b4             |
```

I have to say I have never used anything like this ;-) Matt gave a better real-life usage.

**Comment by pjlsergeant** [comment]
Crikey, OK, I've never seen anything like that. Closing as I'm clearly in error here!

**Comment by paoloambrosio** [comment]
@pjlsergeant correct, but if you don't add titles, descriptions or tags, it makes no sense to split the examples into separate blocks

**Comment by aslakhellesoy** [comment]
The latter. Here is an example:

https://github.com/cucumber/gherkin/blob/master/testdata/good/several_examples.feature

**Comment by aslakhellesoy** [comment]
Can we close this issue?

**Comment by aslakhellesoy** [comment]
Nm - it's already closed :-)
