### ISSUE TITLE
There is no way to work with uploaded files with javascript

### ISSUE THREAD

**Issue by bharath-kairos** [cucumber/gherkin#183]
### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by bharath-kairos** [comment]
Its always taking uri of the feature file. But if user uploaded a file he wont get uri incase of js. So if they provide option to parse file content then it is good.

**Comment by mpkorstanje** [comment]
Hi, I don't really understand what the issue is that you're trying to describe. Could you elaborate, and perhaps provide a concrete example?
