### ISSUE TITLE
[gherkin-cpp, messages-cpp] unable to use Cmake FetchContent to include gherkin-cpp as-source.

### ISSUE THREAD

**Issue by daantimmer** [cucumber/gherkin#192]
### 👓 What did you see?

It is currently not possible to use CMake's FetchContent to include gherkin-cpp and messages-cpp within a project. Both projects are currently setup with a Linux workflow in mind. 'Compile library separately, install library separately, use CMake 'Find' to include the pre-build binary.
This is however not the only way of using CMake projects. Often times it is useful to include the library directly as a dependency, and build the library while building the rest of the project. This especially useful for single-stage builds, instead of multi-stage builds.

### ✅ What did you expect to see?

Being able to FetchContent() gherkin-cpp

### 📦 Which tool/library version are you using?

cmake version 3.27.7

### 🔬 How could we reproduce it?

Will provide an example repository when this is picked up

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

I am building a cucumber runner using cpp. Where gherkin-cpp is the backend for parsing the gherkin files and providing me with a nice json object. The cucumber runner will be made open source (MIT licensed)

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by chybz** [comment]
@daantimmer Thanks for reporting your issue.

FYI it's not a "Linux workflow".

You are responsible to install the dependencies using whatever is appropriate to your specific use case. There are so many options out there and this project does not enforce a specific use case.

It's not clear if you ask for `gherkin/cpp` to `FetchContent` `messages/cpp` or if you encounter issues using `FetchContent` on `gherkin/cpp`.

Would you like to provide further details ?

**Comment by daantimmer** [comment]
I sure will. As I mentioned in my OP.
I have created an example project. Using our own open source devcontainer, which contains gcc, clang and clang-cl to cross compile for windows. The project can be found here: https://github.com/daantimmer/gherkin-cpp-container

One of the usecases that exists is the following: add the required dependencies using `FetchContent`. See:
- https://github.com/daantimmer/gherkin-cpp-container/blob/master/extern/cucumber/gherkin/CMakeLists.txt
- https://github.com/daantimmer/gherkin-cpp-container/blob/master/extern/cucumber/messages/CMakeLists.txt
- https://github.com/daantimmer/gherkin-cpp-container/blob/master/extern/nlohmann/json/CMakeLists.txt

This is the only way to get things `FetchContent`-ed correctly together with `FindPackage`.

As you can see in this CI/build run: https://github.com/daantimmer/gherkin-cpp-container/actions/runs/6855495998 none of the targets can build. That is because all the libraries and executables within `gherkin-cpp` and `messages-cpp` have been setup using `CMAKE_SOURCE_DIR`.

`CMAKE_SOURCE_DIR` uses the _root_ `CMakeLists.txt`. Which does not work in the case of `FetchContent`, because the `CMAKE_SOURCE_DIR` is completely wrong for the directory tree created by `FetchContent`.

I've created a fork of `cucumber/gherkin` and `cucumber/messages` in which I am trying to 'fix' this. To get it to a compiling state:
- https://github.com/cucumber/gherkin/compare/main...daantimmer:gherkin:main
- https://github.com/cucumber/messages/compare/main...daantimmer:messages:main

For the messages repository I had to leave in the `target_include_directories` for `cucumber-messages`, because util.hpp is (accidentally?) residing in the same directory as all the sources. I would assume it has to move to the `include` directory.

After these fixes are applied the projects are atleast able to be configurable and getting to a stage where they can start compiling. As can be seen here:
https://github.com/daantimmer/gherkin-cpp-container/actions/runs/6856150561 
Although, now many other actual build errors pop-up, which is part of #191

**Comment by daantimmer** [comment]
@chybz any input from your side?

**Comment by daantimmer** [comment]
@chybz any input from your side?

**Comment by chybz** [comment]
@daantimmer sorry for the late update, was busy elsewhere. Made some updates and progress, though nothing is finished yet. Fixes should be available within a couple of days now, if I'm not "distracted".

**Comment by daantimmer** [comment]
@chybz note that I've already made quite some changes in my fork for both gherkin-cpp and messages-cpp. Perhaps you can take inspiration from there for all minimum required changes.

**Comment by daantimmer** [comment]
I've added the gherkin pull request: https://github.com/cucumber/gherkin/pull/202

**Comment by chybz** [comment]
Closing as issue fixed by work on #202
