### ISSUE TITLE
Make backgrounds taggable

### ISSUE THREAD

**Issue by jfinkhaeuser** [cucumber/gherkin#198]
Relating to #197 for locale testing, you can run into issues with fairly lengthy user flows, that logically belong in separate scenarios, but practically must become backgrounds for other scenarios.

The canonical example might be new user registration.

``` gherkin
Feature: registration
  Scenario Outline: registration
    Given I see the registration form
    When I do something "<language specific>"
    And I do some more, lengthy steps because the registration is really convoluted

  @en
  Examples:
    | language specific |
    | en                |
```

Then you might have a feature/scenario that depends on a newly registered user. Naively you would do this:

``` gherkin
Feature: something

  Background:
    Given I see the registration form
    When I do something "en"
    And I do some more, lengthy steps because the registration is really convoluted

  Scenario Outline: blah
    Steps with <language specific> stuff

  @en
  Examples:
    | language specific |
    | en                |
```

Except now the `Scenario Outline` lets you localize tests with an example table, but the `Background` is locked into a hardcoded language.

Note that #56 would solve the issue quite nicely. A perhaps lighter-weight alternative would be to be able to tag `Background`:

``` gherkin
Feature: something

  @en
  Background:
    Given I see the registration form
    When I do something "en"
    And I do some more, lengthy steps because the registration is really convoluted

  @fr
  Background:
    Given I see the registration form
    When I do something "fr"
    And I do some more, lengthy steps because the registration is really convoluted

  Scenario Outline: blah
    Steps with <language specific> stuff

  @en
  Examples:
    | language specific |
    | en                |
```

Honestly, the #56 approach is vastly more readable; this issue is more to document a use case where suites (cucumber/cucumber-ruby#821) don't quite solve the issue.

**Comment by jenisys** [comment]
While I do not completely oppose your feature request for "taggable backgrounds", there are a number of questions that must be answered before this functionality can be provided, like:

* What happens when all tagged Backgrounds are disabled/skipped ? 
  Does it even make sense to run the scenarios / scenario outline in the feature file 
  (because some kind of setup is probably missing)
* Do we need an "else / otherwise" background that is used when all the other tagged backgrounds are disabled ?
* ...
