### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/gherkin#201]
Can we please release gherkin 4.0.0? I believe it is currently waiting for #189 but that PR appears to have a lot left to do. I think its important to get changes out so they can be used and releasing major versions shouldn't be a big deal. A major version just means a breaking change. As long as upgrading is well documented, dealing with multiple major version updates isn't hard.

**Comment by enkessler** [comment]
I agree with everything that you just said except for #189 having a lot of work left. It's a minor tweak that needs to be done across all of the languages and it's already been done for at least 3 of them. There's a couple hours of effort there, tops. I'll just go and do that myself...

**Comment by charlierudolph** [comment]
I'm happy to help with that PR as well

**Comment by enkessler** [comment]
I'm going to work on Go and Java. Go ahead and claim a language if you've got a favorite. Alternatively, feel free to merge #194, if you've got the privileges.

**Comment by enkessler** [comment]
Done!

**Comment by aslakhellesoy** [comment]
All the packages except [gherkin-perl](https://github.com/cucumber/gherkin-perl) have been released according to the release process described in [CONTRIBUTING.md](https://github.com/cucumber/gherkin/blob/master/CONTRIBUTING.md#make-a-release). The main repo and all the released repos have been tagged.

The [perl release instructions](https://github.com/cucumber/gherkin-perl/blob/master/CONTRIBUTING.md) currently don't work - the `predistribution` target assumes that `../testdata` is available. The directory is available from the [gherkin](https://github.com/cucumber/gherkin-perl), but not from the [gherkin-perl](https://github.com/cucumber/gherkin-perl) repo, where the release should be made from. (All the other packages have their releases made from the `gherkin-*` repos.

Can you help us with this @pjlsergeant?

**Comment by pjlsergeant** [comment]
I can certainly make the release - fixing the wider issue needs a little bit of thought.

**Comment by pjlsergeant** [comment]
Perl version released as per Gitter discussion

**Comment by charlierudolph** [comment]
Thanks @aslakhellesoy!
