### ISSUE TITLE
How to handle contexts?

### ISSUE THREAD

**Issue by inf3rno** [cucumber/gherkin#205]
I have this simple example:

```cucumber
	Given John is authorized to remove items from the todo list
	When John removes an item from the todo list
	Then the item should be removed from the todo list
```

As you can see I have a lot of duplication here just to make it clear in every line what context I am talking about.

```cucumber
	Given a todo list with items
	And John is authorized to remove items
	When John removes an item
	Then the item should be removed
```

My problem with this solution that if I remove the context from each line, then I have to write abstractions for testing different type of collections. So for example a CollectionTestHelper interface with a ListTestHelper and a MapTestHelper and so on... Otherwise I cannot have the same logic with the last 3 lines.

Other possible solution could be to use the context to distinguish between test implementations. Something like

```js
module.exports = function () {
  this.Given(/^a todo list with items$/, function (callback) {
	this.Given(/^John is authorized to remove items$/, function (){
		//todo list specific logic
	});
	// ...
  });
  
  this.Given(/^a set of tags$/, function (callback) {
	this.Given(/^John is authorized to remove items$/, function (){
		//tag set specific logic
	});
	// ...
  });
  
  this.Given(/^a currency map with 3 character currency codes as keys$/, function (callback) {
	this.Given(/^John is authorized to remove items$/, function (){
		//currency map specific logic
	});
	// ...
  });
};
```

(I am not sure whether this is possible with the current cucumber-js implementation. I guess it isn't.)

Do you have any best practices to deal with contexts?

**Comment by aslakhellesoy** [comment]
This is a bug tracker, not a [support forum](https://cucumber.io/support)

**Comment by inf3rno** [comment]
k.
