### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/gherkin#208]
Ideally I would hope the process could be:
- update the version wherever needed (the ruby gemspec, the javascript package.json, etc...) 
- commit with a tag
- on a tag, travis ci performs the following (once per language)
  - push each subtree and add a tag to each subtree
    - using a github auth token, belonging to a cucumber-bot account
  - publish
    - using a package manager auth key, belonging to a cucumber-bot account

Since we are no longer updating the subtree directly, the need for pulling the subtree should be removed.

Please let me know if you see any problems with this approach. If you think its sufficient, I'm happy to help get this up and running.

**Comment by charlierudolph** [comment]
Travis has some built in help for automating releases to certain package managers. https://docs.travis-ci.com/user/deployment/

**Comment by aslakhellesoy** [comment]
I haven't found a way to push tags to subtrees. And even if you found a way to do that, we shouldn't, because many (but not all) of the package managers perform tagging during a release.

Or maybe we could disable automatic tagging for all package managers?

Were you thinking that all releases would be made by travis' subtree builds?

**Comment by charlierudolph** [comment]
Yes disable automatic tagging. And for tagging the  sub tree, I would think the build could clone the sub tree repo after pushing it and just tag the latest commit.

**Comment by aslakhellesoy** [comment]
Go for it and see what you can come up with!

**Comment by charlierudolph** [comment]
Alright I'll try this for the javascript version to start. Two things I would like to have to start: 
* a github auth token (with write access to the the gherkin repos version, [instructions](https://help.github.com/articles/creating-an-access-token-for-command-line-use/)) 
* a npm auth token (with publish access for the gherkin module, [instructions](https://docs.npmjs.com/all#getting-an-authentication-token))

For each I think we should create a `cucumber-bot` account. For that would probably be good to have them attached to a "cucumber.io" email.

Those could then be added as env variables [here](https://travis-ci.org/cucumber/gherkin/settings) with the names GITHUB_AUTH_TOKEN and NPM_AUTH_TOKEN.
