### ISSUE TITLE
Gherkin testdata duplication

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/gherkin#21]
### 🤔 What's the problem you've observed?

Testdata for gherkin are duplicated into each implementation. In case of update of the testdata, it generates huge diffs which are making PRs difficult to review properly (cf. cucumber/common#1741)

### ✨ Do you have a proposal for making it better?

Stop duplicating testdata and refer to those using relative paths
Or at least duplicating the testdata during the build, but ignoring those from the repo

### 📚 Any additional context?

Why the purpose of the duplication? Is it because of the subrepos? 

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by mpkorstanje** [comment]
Partially fixed with https://github.com/cucumber/gherkin/pull/3

**Comment by mpkorstanje** [comment]
Good enough for now. Dart is it's own problem.
