### ISSUE TITLE
Add 'path' to output of parser

### ISSUE THREAD

**Issue by Zearin** [cucumber/gherkin#213]
## Problem

I want to call `parse()` and be able to access the path to the `*.feature` file that was parsed.
## Recommendation

Add `path` to `GherkinDocument.feature.location` (i.e., the output of `parse()`).
## Rationale

Currently, the parser output has a `location` for just about everything it contains. However, these `location` fields only have `line` and `column`.  

Since a feature represents a physical file, it seems odd that there is no way to access the `path` from the result of a `parse()`.  

Also, the `compile()` function needs a `feature` and a `path`.  If you pass a filename to `parse()`, then `compile()` should be able to grab the path from the result.  

If the parser received a string instead of a filename, then `GherkinDocument.feature.location` could simply be set to `null`/`nil`/`None`.

**Comment by Zearin** [comment]
@aslakhellesoy ping

**Comment by Zearin** [comment]
@aslakhellesoy Whoa!  Issue closed?  Can you at least comment on what I wrote?

**Comment by aslakhellesoy** [comment]
Hi @Zearin. The entire repo has moved, and I didn't want to move over all open issues. Did you see the comment in ae7c92f?

What you're asking for is actually supported in the latest release. You have the `uri` attribute on the [`gherkin-document`](https://docs.cucumber.io/event-protocol/#gherkin-document) event.

**Comment by enkessler** [comment]
A feature's location _is_ the line and column number where it appears in a document. The document itself would have a path location, sure. Something like `GherkinDocument.uri` would be appropriate.

Edit: Ninja'd by Aslak
