### ISSUE TITLE
Do not exclude comments line from current line

### ISSUE THREAD

**Issue by matiasballester** [cucumber/gherkin#216]
Hi, I'm working in a project that requires to do not exclude the comments from the actual node.
i.e.:
Scenario: First Example
This is the description
#Is important to do not exclude this comment line from scenario description string.

Is there a way to make it possible?.

Thanks,
Matias

**Comment by aslakhellesoy** [comment]
Please explain in more detail what you mean by *exclude*. Excluded from *what*?

**Comment by aslakhellesoy** [comment]
Can you also please explain why you need this?

**Comment by matiasballester** [comment]
Hey, thanks for the answer.

We are using the gherkin parser to after read the feature file publish it's content in a confluence page. So, sometimes we include some important information for the Feature/Scenario by using the # char.

It's a requirement to display it in the confluence page.

Right now, since the comments are being excluded from the actual node and added to a Comments's list, there is no way to display in the correct place where it was originally added in the .feature file.

Thanks,
Matias

**Comment by aslakhellesoy** [comment]
Can you give me a concrete example of what kind of information you'd want to have on a line starting with a `#` character?

> Right now, since the comments are being excluded from the actual node and added to a Comments's list, there is no way to display in the correct place where it was originally added in the .feature file.

You should be able to reconstruct it - every node (including comment nodes) have line numbers.

**Comment by matiasballester** [comment]
Sure, this is a concrete example:

Feature: Block Trade Analysis
Give content to what the market(s) activy was trading at during the time
#For Market Date, Contact will use the Security Def.

Scenario: Identify the worst price
The core measure to determine if a trade was executed at a reasonable price is to establish a baseline price range.
#In the scenario, we will look a single point in the book and verify we are calculation the worst price for several quantities.

Right now, all the comments line are not part of the Feature object, are added to the comment's list. I would like to have the first # added to the Feature.description field, and the second one to the ScenarioDescription.description field.

**Comment by enkessler** [comment]
The simplest thing to do would be to not make them comment lines. If you are writing them along with the description and you want them to appear with the description and the information is an important part of the description, then I would contend that the comment lines are, in fact, description. So don't mark them with '#'.

You can still indicate that they are 'secondary information' if you want to. For example:

    (For Market Date, Contact will use the Security Def.)

     - For Market Date, Contact will use the Security Def.

    Note: For Market Date, Contact will use the Security Def.

Just don't use '#' unless you really mean 'this is not important information'.

**Comment by aslakhellesoy** [comment]
Why do you need to put a `#` in front of these sentences? Why don't you just write this:

```gherkin
Feature: Block Trade Analysis
  Give content to what the market(s) activy was trading at during the time
  For Market Date, Contact will use the Security Def.

  Scenario: Identify the worst price
    The core measure to determine if a trade was executed at a reasonable price is to establish a baseline price range.
    In the scenario, we will look a single point in the book and verify we are calculation the worst price for several quantities.

    Given ...
```

**Comment by matiasballester** [comment]
Yes, I agreed. It's a business requirement.So, that's why I was trying to understand if there is a way to include comments as part of Feature object. Thanks a lot anyway. I'll suggest your option.
