### ISSUE TITLE
Intermittent failure of cpp test jobs in CI

### ISSUE THREAD

**Issue by kieran-ryan** [cucumber/gherkin#217]
### 👓 What did you see?

Observed instances where the cpp jobs appear to have failed - with changes being unrelated to the cpp job itself e.g. modifying markdown files. For example, the following [failed run](https://github.com/cucumber/gherkin/actions/runs/7545566347/job/20541479511?pr=215) on #215. [Another failed run](https://github.com/cucumber/gherkin/actions/runs/7544434482/job/20537758755). Re-running the job for other PRs resulted in the job succeeding.

Download of latest Ninja build failing. Perhaps rate limiting or network issue?

```console
Run cmake -P cmake/cmate --cc=clang install
CMate: using compilers CC=clang CXX=clang++
CMate: checking nlohmann/json
Cloning into '/Users/runner/work/gherkin/gherkin/cpp/.cenv/downloads/nlohmann_json/sources'...
CMate: building with: -DJSON_BuildTests=OFF
CMake Error at cmake/cmate:23 (message):
  CMate: error: download of
  https://api.github.com/repos/ninja-build/ninja/releases/latest failed:
  22;"HTTP response code said error"
Call Stack (most recent call first):
  cmake/cmate:186 (cmate_die)
  cmake/cmate:212 (cmate_download)
  cmake/cmate:262 (cmate_github_get_latest)
  cmake/cmate:282 (cmate_check_ninja)
  cmake/cmate:1127 (cmate_set_ninja)
  cmake/cmate:1256 (cmate_install_cmake_dep)
  cmake/cmate:1270 (cmate_install_dep)
  cmake/cmate:1315 (cmate_install_repo)
  cmake/cmate:1474 (cmate_install)
  cmake/cmate:1474 (cmake_language)
  cmake/cmate:1493 (cmate_process_cmd)


Error: Process completed with exit code 1.
```

### ✅ What did you expect to see?

Cpp job succeeds.

### 📦 Which tool/library version are you using?

Running with tooling versioned in repo against commit 579c66d.

### 🔬 How could we reproduce it?

Intermittent failure with pipelines. Not sure of root cause. Issue should arise with subsequent pipelines.

### 📚 Any additional context?

Apologies if raised under an existing issue - have not yet located.

**Comment by chybz** [comment]
author/maintainer of cpp port here, will keep an eye on that issue and hopefully find a proper solution to circumvent this problem tomorrow.

**Comment by kieran-ryan** [comment]
Noting a reoccurrence, just in case useful info that it wasn't a one-off - though works on retry so all good 👍
https://github.com/cucumber/gherkin/actions/runs/8654231965/job/23731035018

**Comment by chybz** [comment]
Yep, many thanks for the report @kieran-ryan, it's a timeout/connection reset while trying to download an additional build tool (ninja). A proper fix is in the way (half baked already). Will try to find some time and a bit of brain juice to tackle it.
Have a good day !
