### ISSUE TITLE
cucumber.el not worked with gherkin version 4.

### ISSUE THREAD

**Issue by zw963** [cucumber/gherkin#217]
Here is the `rb` file included with cucumber.el.

https://github.com/michaelklishin/cucumber.el/blob/master/support/find_step.rb

It not worked at all.

Please give a clue about how to refactor this file or the last version which could be used.

Thanks.

**Comment by aslakhellesoy** [comment]
This is a bug tracker, not a support forum.
Please find help at https://cucumber.io/support
