### ISSUE TITLE
Support “full width colon：（U+FF1A）”as title keyword separator“

### ISSUE THREAD

**Issue by lxbzmy** [cucumber/gherkin#220]
In CJK (Chinese, Japanese and Korean) computer writing，they always use full with colon：“：”。
Especially Non-computer professionals（As a programer we always know “:” is different from “：”，but many testers has poor program knowledge，they always use wrong colon）。

For example：

```
#language:zh-CN
功能: google search

  背景: broswer open google.com
    * chrome www.google.com

  场景:
    假如 find #search
    并且 input hello world
    那么搜索结果出现
```

```
#language:zh-CN
功能：google search

  背景： broswer open google.com
    * chrome www.google.com

  场景：
    假如 find #search
    并且 input hello world
    那么搜索结果出现
```

As we can see，“:” and “：”  has the same semantics。Especially cucumber is a bdd framework has i18n support.

reference：
https://en.wikipedia.org/wiki/Colon_(punctuation)
https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms#Full

There is another reason lead to full with colon important than other full with punctuation。
IME alway output full width colon when they are CJK mode。

**Comment by aslakhellesoy** [comment]
If you want this, please submit a pull request to https://github.com/cucumber/cucumber
