### ISSUE TITLE
Document toolchain

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin#222]
What's the minimum toolchain to start contributing? Depends on target platform.

**Comment by brasmusson** [comment]
@ciaranmcnulty To only provide an implementation in a new language, I would say that what is needed is to install the dependencies that enables running `cd dotnet; make` (that is building the .NET version). I think the things needed are (subset of the [prerequisites](https://github.com/cucumber/gherkin/blob/master/CONTRIBUTING.md#building)):
* .NET or Mono (needed to run `berp` to generate parsers)
* `make`
* `jq` (>= 1.4 for `--sort-keys` option)
* `diff`
* `git`

**Comment by ciaranmcnulty** [comment]
Thanks @brasmusson, I'll try and verify this
