### ISSUE TITLE
A space following Escape \ as the last character of a table line instead of | causes StopIterationError not CompositeError

### ISSUE THREAD

**Issue by isparks-tg** [cucumber/gherkin#223]
### 👓 What did you see?

A table of the form

```
Some step with table:
    | Name | Value |
    | A        | 1        \
```
Where a SPACE follows the last \ (if the space is not present then the error does not exhibit)

Python example:

```python
from gherkin.parser import Parser
from gherkin.token_scanner import TokenScanner

feature_text = """
Feature: As a developer I want to report a bug

   Scenario: Bad table escape
      When I have a table
         | Name | Value |
         | A    |       \ """
                        # ^- Note space
parser = Parser()
parser.parse(TokenScanner(feature_text))
```

Will fail the parser because of StopIteration.

### ✅ What did you expect to see?

A CompositeParserException raised with position of error - which is what is seen if the space is removed

### 📦 Which tool/library version are you using?

python gherkin_official-4.1.3 but I believe exists in current github code also related to split_table_cells in gherkin_line.py

### 🔬 How could we reproduce it?

1. Install gherkin-official.' version 'gherkin_official-4.1.3'
2. Create a file called 'gherkin_test.py' with the contents above
3. python gherkin_test.py
4. See error 'RuntimeError: generator raised StopIteration'

**Comment by mpkorstanje** [comment]
Oh nice find. Would you be interested in creating a PR to fix this? We currently don't have a maintainer with a lot of experience in Python.
