### ISSUE TITLE
Provide a VM

### ISSUE THREAD

**Issue by ciaranmcnulty** [cucumber/gherkin#224]
There's such a high volume of platform dependencies if you want to be able to make every version - a Vagrant box, or a docker-compose thing with all that stuff ready to go would be ideal

**Comment by merrua** [comment]
I think this would also be useful. It would really help with introducing new people to cucumber.

**Comment by jenisys** [comment]
@ciaranmcnulty 
It depends what you actually want to do. If you want to have Eclipse installed with the Cucumber plugin (meaning a GUI-centric working environment), a virtual machine with vagrant is the way to go (at least for me). If you only want to have a shell-like environment, docker may be better suited. With both approaches you could provide a prepared vagrant box or docker image on a hub for others to use easily.

But before we start, we would need to have a blueprint/recipe what needs to be installed (for provisioning of the virtual machine or docker image). And a decision what OS should be used ... (Linux, macOS/OSX)

**Comment by aslakhellesoy** [comment]
I think what @ciaranmcnulty meant is to make it easier for people to contribute to the gherkin codebase.
