### ISSUE TITLE
Add language json content to Parser constructor

### ISSUE THREAD

**Issue by mauriciotogneri** [cucumber/gherkin#226]
Allow to pass the content of the **gherkin-languages.json** to the **Parser** instead of assuming that it will be in the resources.

If the language json is passed as a parameter, use it, otherwise fallback to the current implementation.

Very useful for **Android** projects where resource files are not expected to be in the folder "resources".

**Comment by aslakhellesoy** [comment]
LGTM!

**Comment by aslakhellesoy** [comment]
If you want this, please send a pull request to https://github.com/cucumber/cucumber (gherkin's new home)
