### ISSUE TITLE
Adding kind of an Example table in the Background steps

### ISSUE THREAD

**Issue by NiPelissier** [cucumber/gherkin#226]
### 🤔 What's the problem you're trying to solve?

As far as I know, it is not possible to use examples tables in background step. This feature could allow to run multiple times scenario of a feature with differents given steps.

It could be nice to be able to do something like this:

Feature: aFeature
    Background
        Given user1 is <aParam>

        Examples
            |           aParam               |
            | connectedWithFirefow |
            |   connectedWithEdge  |

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mpkorstanje** [comment]
To help us understand this feature request a bit better, what is the underlying problemen you are trying to solve? Do you have a more comprehensive example?

Historically speaking, the general consensus has been that programming features don't belong in Gherkin. As they make the scenario much harder to understand for non-technical users.

It would for example be difficult to determine just by reading which examples are used where. Especially when an example table is used in the background in combination with with a scenario outline.

As a workaround, what usually does work is to create a list of things (e.g. users) using a data table in the given step of the background.  All scenarios then use all these users.
