### ISSUE TITLE
Running a cucumber script flags another feature file that shouldn't be called and complains of parser error

### ISSUE THREAD

**Issue by DougMaisells** [cucumber/gherkin#227]
```@peak @doug_departments
Feature: Peak departments

  Background:
    Given I sign in to mediamanager using the default user
    And I go to the home page in Peak

@create_edit
  Scenario: Create a department
    When I go to the Admin page in Peak
    When I click on the "Manage Departments" link under the "Bodies" panel in the Peak Admin Navbar
    And I delete the department "Department-Automated" on the DepartmentAdminPage in Peak if it exists
    And I click the create button on DepartmentAdminPage in Peak
    When I create a department in Peak
      | name          | Department-Automated           |
      | abbreviation  | MUD                          |
      | description   | dude, preserve what I am typing|
    Then I wait for a redirect to the "department" page in Peak
    Then I should see "Department-Automated" on the DepartmentAdminPage in Peak
    #And I delete the department "Department-Automated" on the DepartmentAdminPage in Peak
    #Then I should not see "Department-Automated" on the DepartmentAdminPage in Peak

@create_edit
  Scenario: Edit a department
    When I go to the Admin page in Peak
    When I click on the "Manage Departments" link under the "Bodies" panel in the Peak Admin Navbar
    Then I should see "Department-Automated" on the DepartmentAdminPage in Peak
    When I edit the department "Department-Automated" in Peak
      | name          | Department-Automated           |
      | abbreviation  | ABC                            |
      | description   | updated description            |

# currently fails on the create unique expected 1-3 arguments but got none
@unique
Scenario: Create a unique department in Peak
  When I go to the Admin page in Peak
  When I click on the "Manage Departments" link under the "Bodies" panel in the Peak Admin Navbar
  And I click the create button on DepartmentAdminPage in Peak
  When I create a unique department in Peak

#  @error_message
  #Scenario: Try to create with out a name
  #  When I go to the Admin page in Peak
  #  When I click on the "Manage Departments" link under the "Bodies" panel in the Peak Admin Navbar
  #  When I create a department in Peak
  #  Then I should see the error "Please enter a Department Name or select a unique Department Name." on the DepartmentFormPage in Peak

  #  @minimal
  #  Scenario: Create with only a department name
#      When I go to the Admin page in Peak
#    When I click on the "Manage Departments" link under the "Bodies" panel in the Peak Admin Navbar
#      And I click the create button on DepartmentAdminPage in Peak
##        | name  | Department of motor vengence                      |
#      Then I wait for a redirect to the "department" page in Peak
#      Then I should see "Department of motor vengence" on the DepartmentAdminPage in Peak
#      And I delete the department "Department of motor vengence" on the DepartmentAdminPage in Peak
#      Then I should not see "Department of motor vengence" on the DepartmentAdminPage in Peak

```##todo: no duplicate names, abreviation renders


When I run this script, it complains of a feature file that is a separate script and shouldn't even be called by this script.  My co-worker thinks there may be a merge conflict because the only thing i did between the time it was working and not is commit all whole bunch of files, and re-pull the repo (may have had to do a stash or stash pop in there somewhere).  Forgive me, I am NOT a developer and really don't know what i am doing exactly and could use somebody to straighten me out.  But the fact that another file is flagged that is not being invoked makes no logical sense to me so that's why I am flagging: features/peak/bodies/pk_bodies.feature: Parser errors:

<img width="1008" alt="screen shot 2016-08-26 at 7 09 20 am" src="https://cloud.githubusercontent.com/assets/12070836/18006292/23190f64-6b5c-11e6-9382-8628bb4617d5.png">

**Comment by DougMaisells** [comment]
LOL, trying to append files to help the person working on this cucumber ticket and the ticket doesn't even support pasting .feature files to the ticket.  That's funny?  So you can't post .feature or .rb files here?

**Comment by DougMaisells** [comment]
[doug_department.feature.txt](https://github.com/cucumber/gherkin/files/439310/doug_department.feature.txt)
[pk_bodies.feature.txt](https://github.com/cucumber/gherkin/files/439311/pk_bodies.feature.txt)

**Comment by DougMaisells** [comment]
See my command snapshot above.  I use tags that are specific to the doug_department.feature.txt file.   Why is the cucumber interpretor complaining about this other file; it shouldn't even be called?

**Comment by DougMaisells** [comment]
A co-worker helped me and there was a ====== in the pk* file which was causing cucumber command to fail.  You mean to tell me when I run cucumber that even though I scope it to look for scripts with particular tags that the cucumber command does a syntax check of all feature files in your repo and complains of errors in them.  That seems kind of dumb.  Especially if you were working on a set of scripts at one time and one set was a WIP with plenty of errors and the others were ready to test.  You'd never be able to work this way.  Cucumber scripts should be ignored that are not included by the tags provided by the user.  Makes no intuitive sense how this works

**Comment by enkessler** [comment]
@DougMaisells If you want to filter your scripts based on their tags, then Cucumber will, naturally, have to read your scripts first in order to determine what tags are in them. Based on the tags that you want to filter, Cucumber will not _execute_ certain scripts, but it must _read_ all of them.

**Comment by DougMaisells** [comment]
By reading them, you mean running through a pre-compiler (syntax checking)?

Also getting hung up on the cryptic output.  This is from Cucumber, Selenium, or what?

How do you recommend then a person working on a set of scripts in a repo maybe in one area, stopping, and then working in another area, completing that area, running a script for that area and realizing "oh, I need to correct all syntax errors in my other scripts first".   Seems like there should be away then to read just tags at the top of the file and if there is not a match, ignore the rest of the file.  Just saying....

Douglas.Maisells@granicus.com
[email-Sig_peak2]

**Comment by enkessler** [comment]
> By reading them, you mean running through a pre-compiler (syntax checking)?

Yep.

> Also getting hung up on the cryptic output.  This is from Cucumber, Selenium, or what?

That's a stack trace from the gherkin gem. It's letting you know what line of the file it choked on (in this case: line 87 and column 1), what would have been a valid thing to come next (another step line, a tag, etc.), and what it found instead (a bunch of '=' characters).

> How do you recommend then a person working on a set of scripts in a repo maybe in one area, stopping, and then working in another area, completing that area, running a script for that area and realizing "oh, I need to correct all syntax errors in my other scripts first".

I recommend that they not leave incomplete statements lying around. They don't have to write the next scenario. They don't even have to write the next step. They just have finish whatever line that they are on instead of walking away halfway through typing out a thought.

> Seems like there should be away then to read just tags at the top of the file and if there is not a match, ignore the rest of the file.  Just saying....

Tags can appear in parts of the file other than the very top of the feature. There is no point at which we can arbitrarily decide "There's probably nothing important after this line. I'll stop reading now."

> In this case, the "syntax" errors were caused by gitHub with merge conflicts and it demarcated text with <<<<< and <<<<<<<<   and =========   Seems like Cucumber should ignore that if it could.

Those particular demarcations are only meaningful if Git is your source control tool. There a lots of source control tools out there and it is not feasible for _this_ tool (which has nothing to do with source control) to be knowledgeable about how they all insert extra text into files.

**Comment by DougMaisells** [comment]
Eric,
Thank you for the explanation.   I am just venting.  I have never written automatic scripts during my 25 years of testing.  I am trying to learn Cucumber, Ruby, Capybara, Git, and all the other developer jargon not to mention internet/hosted application let alone all the COA conditions on the stories I have to test.    It is very frustrating to have a script working one day and all I did was push my scripts up to a repo, and boom, got a merge conflict, and then cucumber failed.  I hate not having a mentor and I don't function well googling everything.

I guess my advice to the half-baked script scenario is don't call them .feature or .rb files or leave them out of the repository until they have been debugged syntactically.

Do have basic layman's explanation of the cucumber gem and all the nuances that I can avoid this kind of stuff in the future (like Cucumber looks through all feature files for tags, etc.)?

Douglas.Maisells@granicus.com
[email-Sig_peak2]

**Comment by brasmusson** [comment]
> When I run this script

No, actually you are not. The command you used was:
```
cucumber -t @peak -t @doug_departments
```
and that command instructs cucumber to:
* parse all feature files (in the features directory structure), and then 
* execute the scenarios the matches the tags: `@peak`,`@doug_departments`

In this case cucumber cannot finish step one because of a parse error in one file (in `features/peak/bodies/pk_bodies.feature`), and does therefore not continue to step two (executing scenarios from feature files). 

Maybe you knew that there was only one feature file with scenarios matching the tags you specified, but you did not tell cucumber that, so it has to parse the whole of all feature files to find out the tags for the different scenarios in each feature file (as as mentioned in a previous comment tags can appear in may different positions in a feature file). It is possible to tell cucumber to only run scenarios from one specific feature file (or the files in a sub directory structure), in which case cucumber will neither open nor parse any other feature files:
```
cucumber features/sub_dir/name.feature

cucumber features/sub_dir
```
or combined with specifying tags:
```
cucumber -t @peak -t @doug_departments features/sub_dir/name.feature

cucumber -t @peak -t @doug_departments features/sub_dir
```

However when not specifying a specific feature file, you need to make sure that all features files that cucumber finds can be parsed correctly - even though no scenarios would be executed from them due to the specified tags.

**Comment by DougMaisells** [comment]
Bjorn,
As I mentioned to Eric when he replied, do you a list of gotchas or things to keep in mind when using cucumber.
Things such as this.

Douglas.Maisells@granicus.com
[email-Sig_peak2]

**Comment by DougMaisells** [comment]
Any other Cucumber cheat sheet, good practices, gotchas, would be appreciated so I can avoid spinning my wheels in the future.

**Comment by DougMaisells** [comment]
Cucumber support,


Forgive me, if there is a proper channel to direct this question to cucumber support, please let me know?


·      How does one write a main "smoke" test that invokes a subset of feature file scenarios in a particular order? True, you could put the same tag on each feature file consisting of scenarios but then how do you dictate what order the individual feature files are executed?  Can you invoke other scenarios located in other feature files with a cucumber command inside a scenario or do you have to replicate all the gherkins for individual feature file into the main "smoke" driver test?


Douglas.Maisells@granicus.com

**Comment by enkessler** [comment]
Here is the link to the help forum: https://groups.google.com/forum/#!forum/cukes

To answer your question: As a rule, one does not order their tests. Order dependency makes tests more fragile and harder to debug and maintain.

**Comment by DougMaisells** [comment]
How does one then automate a set of tests that are run in a particular order to emulate a customer going into a system a following a recommended procedure for provisioning data?   I'd like to use for example a department created on one form on another form (a meeting).

Personally order dependency is way down the chart as far as list of importance.  Navigating the whole capybara library, DOM, and working with github and merge conflicts is much more oppressive at the moment.    Get something working and go back and tweak later.

If my sequence of tests failed in this regard (for example department wasn't created), I would just modify the department failure in the gherkin script and re-execute.  Simple.

Douglas.Maisells@granicus.com
[email-Sig_peak2]

**Comment by DougMaisells** [comment]
Obviously I am missing key concepts like this.  My company just throws me into the fire and expects me to absorb all this in some manner.  Is there an online class or something to read to go over generalized automation good-practices?

Douglas.Maisells@granicus.com
[email-Sig_peak2]

**Comment by enkessler** [comment]
This issue thread has gotten a bit long. Please create a new thread over on the help forum.

**Comment by aslakhellesoy** [comment]
@DougMaisells this is a bug tracker, not a help forum.

Please try https://cucumber.io/support and https://cucumber.io/school

**Comment by DougMaisells** [comment]
Sorry Eric Kesler gave me the link, blame him

Douglas.Maisells@granicus.com
[email-Sig_peak2]

**Comment by enkessler** [comment]
@DougMaisells I gave you the link to the mailing list/help forum. That link can also be found through the support link that @aslakhellesoy gave you.
