### ISSUE TITLE
Add block/loop/set alternatives to repeat set of scenarios

### ISSUE THREAD

**Issue by vveliev** [cucumber/gherkin#228]
Hey I'm currently refactoring some old cucumber implementation , where tt2 templates were user to extend cucumber.

Ex.
I have 2 items of a product and configuration file where one product valid for 5 years and another is only for 3.

now I would like to have test looks like that:

``` rb
Feature: expire years
  Scenario: 1 test year
   Given years 1
   Then step 2
   Then step 3

  Scenario: validate product is for year 1 
    Step 1 <path>  
    Step 2 <val>
  Examples:
  |key   | val  |
  | path| /test/data/year/1|

  Scenario: 2 test year
   Given years 2
   Then step 2
   Then step 3

  Scenario: validate product is for year 2
    Step 1 <path>  
    Step 2 <val>
  Examples:
  |key   | val  |
  | path| /test/data/year/2|

```

and shorter version

``` rb
 Block: years to 
  Scenario: <<year>> test year
   Given years <<year>>
   Then step 2
   Then step 2

  Scenario outline: validate product is for year <<year>>  
    Step 1 <path>  
    Step 2 <val>
  Examples:
  |key   | val  |
  | path| /test/data/year/<<year>>|
Data_set:
| year |
| 1      |
| 2      |
```

And i would also assume that it would be useful to have ability to have ability access Cucumber world from `Block` such that some dynamic values can be loaded from configs.

**Comment by aslakhellesoy** [comment]
This is a big change, and I don't want to add more "programming" constructs to Gherkin. Feel free to discuss in one of the [support](https://cucumber.io/support) forums for an alternative approach.

**Comment by vveliev** [comment]
It is, but it also makes cucumber more flexible, simplicity is good, but it some cases it makes writing of the test's more complicated.
