### ISSUE TITLE
Why can't I use Given/When/Then multiple times in the same feature? 

### ISSUE THREAD

**Issue by mariogintili** [cucumber/gherkin#231]
The following feature fails

```gherkin
  Scenario: No bills to show
    Given I visit the bot page
    When I have no bills
    When I type in "I want to view my bill"
    Then the bot understands and calls view-bill
    And I should be on /bills
    And I should see a message saying I have no bills left
```

A fellow developer said to me "You can't only use When once" why is this? same question applies to only being able to use `And` for `Given` and `Then` and not for `When`

Seems like something that should be supported 😄  but maybe there's a good reason why not?

[EDIT] I was using [ember-cli-yadda](https://github.com/curit/ember-cli-yadda/) when I ran into this

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by mariogintili** [comment]
@aslakhellesoy sorry had no idea cucumber was a private company

**Comment by aslakhellesoy** [comment]
@mariogintili you're right that the Cucumber open source project is sponsored by a company by the same name as of 2014, but that's not why we're asking people to use the mailing lists and chat for questions.

We've encouraged this behaviour since the birth of the project in 2008. Keeping conversations and bug tracking separate just makes the project tidier.

**Comment by mariogintili** [comment]
@aslakhellesoy I'll raise on gitter thank you - although in all due honesty is easy to get the wrong image when there's a paid version on the support page 😄

**Comment by aslakhellesoy** [comment]
What makes you think you got the wrong image?

**Comment by mariogintili** [comment]
@aslakhellesoy the styling made me feel I have to pay to get support - since the paid one seemed like the one that had a CTA on it

**Comment by aslakhellesoy** [comment]
You mean you got the impression you had to pay to use the mailing list or chat room?

**Comment by mariogintili** [comment]
@aslakhellesoy when looking at it superficially I did - I know the message is well worded but sometimes we look at a site for .2 seconds and leave 😄  or maybe its just me
