### ISSUE TITLE
Get table cell content with leading/trailing spaces?

### ISSUE THREAD

**Issue by emiltin** [cucumber/gherkin#232]
I'm trying to use a table like the following, and want to get strings like "   a   " (ie including the leading and trailing spaces).

```gherkin
            |     a     |
            |     b     |
            | d c   g h |
            |     e     |
            |     f     |
````

But Gherking strips the spaces before cucumber can get to them. Is it possible to get the raw string?

Details about the use case is in the ticket over at cucumber-js: https://github.com/cucumber/cucumber-js/issues/640

**Comment by aslakhellesoy** [comment]
Gherkin Data Tables are designed to capture data - the kind you'd typically put in an Excel spreadsheet. As @charlierudolph pointed out, a DocString might be what you're looking for.

What kind of data structure do you use to represent this in your app?

**Comment by emiltin** [comment]
Geographical points with latitude and longitude. We also use an alternative format where we list each points and it's lat and lot, but for most tests, it's much more practical to have this kind of small visual map.

**Comment by aslakhellesoy** [comment]
The example you gave above doesn't look like geo locations to me. I'm more used to seeing them as `[51.5352881,-0.1709425]`.

How does your example translate into geo locations?

**Comment by emiltin** [comment]
It translates into geo locations based on the horizontal and vertical position of the nodes (labelled as a,b,c..). This is why we need to preserve leading spaces.
By default it uses a grid size of 100 meter and an origin at [0,0], both of which can be changed.

**Comment by emiltin** [comment]
You can see an example of real-world tests here:
https://github.com/Project-OSRM/osrm-backend/blob/master/features/guidance/turn.feature

**Comment by aslakhellesoy** [comment]
Ok I see what you mean. Yeah, I'd definitely use a DocString for this - much more pleasant to edit and read. You can easily turn it into an array of arrays:

```js
// Quick ES6 hack
const grid = docstring.split(/\n/).map(row => row.split('').filter((_, n) => n%2==0))
```

**Comment by aslakhellesoy** [comment]
No way to preserve leading and trailing space in table cells I'm afraid. Preserving it would break a lot of code.

**Comment by aslakhellesoy** [comment]
Of course, you could do this if you want:

```
| x |
```
But yiu'd have to strip/process the piped yourself.
