### ISSUE TITLE
new javascript release

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/gherkin#236]
I had a fix I got merged in back in April (46e72cd3cd79965298a9b154af7741480230b916). I have been manually applying that on cucumber-js in order to allow it to run in the browser and would greatly appreciate if I could get a new javascript release to prevent me from having to do that in the future.

**Comment by beeblebrox3** [comment]
I'm having problem running tests of an project that uses the javascript package that this commit solves. Please, release a new version with this change.

Thanks, @charlierudolph

**Comment by charlierudolph** [comment]
@aslakhellesoy bump. Any plans for a new gherkin release?

**Comment by charlierudolph** [comment]
Thanks for this!

**Comment by aslakhellesoy** [comment]
Sorry it took so long! ;-)

**Comment by beeblebrox3** [comment]
Thanks!
