### ISSUE TITLE
No lexer was found for en

### ISSUE THREAD

**Issue by stevelake** [cucumber/gherkin#237]
I have the following gems installed (amongst others - I've attached the full list):
cucumber (2.4.0, 1.3.20)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
gherkin (4.0.0, 2.12.2 x86-mingw32)
gherkin3 (3.1.2)

I'm getting...
WARNING: cannot load such file -- 2.3/gherkin_lexer_en
Couldn't load 2.3/gherkin_lexer_en
The $LOAD_PATH was:
lib
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/bin/../lib
C:/Program Files (x86)/JetBrains/RubyMine 8.0.3/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 8.0.3/rb/testing/patch/bdd
C:/Program Files (x86)/JetBrains/RubyMine 8.0.3/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 8.0.3/rb/testing/patch/testunit
C:/Program Files (x86)/JetBrains/RubyMine 8.0.3/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 8.0.3/rb/testing/patch/bdd
C:/Program Files (x86)/JetBrains/RubyMine 8.0.3/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 8.0.3/rb/testing/patch/bdd
C:/ruby/lib/ruby/gems/2.3.0/gems/debase-0.2.2.beta6/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/multi_json-1.12.1/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/multi_test-0.1.2/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.5.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8.1-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/rack-test-0.6.3/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/xpath-2.0.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/public_suffix-2.0.4/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/addressable-2.5.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/capybara-2.10.1/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/multi_xml-0.5.5/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/httparty-0.11.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/net-http-persistent-2.9.3/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.7.2-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/unf-0.1.4/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/domain_name-0.5.20161021/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/netrc-0.11.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/ffi-1.9.14-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/net-ssh-gateway-1.2.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/websocket-1.2.3/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/cmdparse-3.0.1/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/parallel-1.9.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/parallel_tests-1.3.7/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/sauce_whisk-0.0.21/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/sauce-3.5.11/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/selenium-client-1.2.18/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/process-0.0.1/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.2-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.2-x86-mingw32/ext/oci8
C:/ruby/lib/ruby/gems/2.3.0/gems/i18n-0.7.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/mysql2-0.4.5-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/zscheduler-0.0.6/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/graphite-api-0.1.6/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/pg-0.19.0-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/tiny_tds-1.0.5-x86-mingw32/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/nori-2.6.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/socksify-1.7.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/wasabi-3.5.0/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/gyoku-1.3.1/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/akami-1.3.1/lib
C:/ruby/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib
C:/ruby/lib/ruby/site_ruby/2.3.0
C:/ruby/lib/ruby/site_ruby/2.3.0/i386-msvcrt
C:/ruby/lib/ruby/site_ruby
C:/ruby/lib/ruby/vendor_ruby/2.3.0
C:/ruby/lib/ruby/vendor_ruby/2.3.0/i386-msvcrt
C:/ruby/lib/ruby/vendor_ruby
C:/ruby/lib/ruby/2.3.0
C:/ruby/lib/ruby/2.3.0/i386-mingw32. Reverting to Ruby lexer.
No lexer was found for en (cannot load such file -- gherkin/lexer/en). Supported languages are listed in gherkin/i18n.json. (Gherkin::I18n::LexerNotFound)
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/i18n.rb:108:in `rescue in lexer'
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/i18n.rb:97:in `lexer'
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:139:in `transition_table'
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:128:in `build_transition_map'
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:124:in `transition_map'
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:91:in `initialize'
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:68:in `new'
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:68:in `push_machine'
C:/ruby/lib/ruby/gems/2.3.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:31:in `parse'
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/lib/cucumber/feature_file.rb:37:in `parse'
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/features_loader.rb:28:in `block in load'
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/features_loader.rb:26:in `each'
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/features_loader.rb:26:in `load'
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/features_loader.rb:14:in `features'
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:179:in `features'
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:49:in `run!'
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/lib/cucumber/cli/main.rb:47:in `execute!'
C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/bin/cucumber:13:in `<top (required)>'
C:/ruby/bin/cucumber:23:in `load'
C:/ruby/bin/cucumber:23:in `<top (required)>'
C:/ruby/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_load'
C:/ruby/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_program'
C:/ruby/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide:130:in `<top (required)>'

From a previous solved issue I get the impression that gherkin3 resolves this problem, so I attempted to uninstall gherkin versions 4.0.0 & 2.12.2... However, that fails with "Uninstallation aborted due to dependent gem(s)". If the uninstallation would resolve this problem, how do I discover what are the dependent gem(s) to accomplish it? If not, what is the solution?

[gem_list.txt](https://github.com/cucumber/gherkin/files/596957/gem_list.txt)

**Comment by brasmusson** [comment]
> C:/ruby/lib/ruby/gems/2.3.0/gems/cucumber-1.3.20/bin/../lib

Do not use cucumber v1.3.20.

Uninstall cucumber 1.3.20, gherkin 2.12.2 x86-mingw32 and gherkin3 3.1.2

Then use cucumber v2.4.0

**Comment by stevelake** [comment]
Many thanks for this. I've successfully uninstalled those, but now I get...
Uncaught exception: Could not find 'cucumber' (= 1.3.20) - did find: [cucumber-2.4.0]
Checked in 'GEM_PATH=H:/.gem/ruby/2.3.0;C:/ruby/lib/ruby/gems/2.3.0', execute `gem env` for more information
	C:/ruby/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs'
	C:/ruby/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	C:/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	C:/ruby/bin/cucumber:22:in `<top (required)>'

Running 'gem env' gives me...
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/ruby/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: H:/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: C:/ruby/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/ruby/bin
  - SPEC CACHE DIRECTORY: H:/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/ruby/lib/ruby/gems/2.3.0
     - H:/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - H:\bin
     - C:\ruby\Git\mingw64\bin
     - C:\ruby\Git\usr\local\bin
     - C:\ruby\Git\usr\bin
     - C:\ruby\Git\usr\bin
     - C:\ruby\Git\mingw64\bin
     - C:\ruby\Git\usr\bin
     - H:\bin
     - C:\ProgramData\Oracle\Java\javapath
     - C:\Program Files (x86)\Intel\iCLS Client
     - C:\Program Files\Intel\iCLS Client
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0
     - C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files\Intel\WiFi\bin
     - C:\Program Files\Common Files\Intel\WirelessCommon
     - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0
     - C:\Program Files (x86)\Skype\Phone
     - C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio
     - C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn
     - C:\Program Files\Microsoft SQL Server\110\Tools\Binn
     - C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn
     - C:\Users\stephenla.CW0DOMAIN\Downloads\phantomjs-2.1.1-windows\bin
     - C:\workspace\chrome_driver
     - C:\Users\stephenla.CW0DOMAIN\AppData\Local\apache-jmeter-3.0\bin
     - C:\gecko_driver
     - C:\ruby
     - C:\ruby\bin
     - C:\ruby\bin
     - C:\ruby2.1.8\Ruby2.2.0\bin
     - C:\ProgramData\Oracle\Java\javapath
     - C:\Program Files (x86)\Intel\iCLS Client
     - C:\Program Files\Intel\iCLS Client
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0
     - C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files\Intel\WiFi\bin
     - C:\Program Files\Common Files\Intel\WirelessCommon
     - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0
     - C:\Program Files (x86)\Skype\Phone
     - C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio
     - C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn
     - C:\Program Files\Microsoft SQL Server\110\Tools\Binn
     - C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn
     - C:\ruby\Git\cmd
     - C:\ruby\Git\usr\bin\vendor_perl
     - C:\ruby\Git\usr\bin\core_perl

What do I need to do to remove this requirement for cucumber 1.3.20?

**Comment by stevelake** [comment]
Many thanks for this. I've successfully uninstalled those, but now I get...
Uncaught exception: Could not find 'cucumber' (= 1.3.20) - did find: [cucumber-2.4.0]
Checked in 'GEM_PATH=H:/.gem/ruby/2.3.0;C:/ruby/lib/ruby/gems/2.3.0', execute `gem env` for more information
	C:/ruby/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs'
	C:/ruby/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	C:/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	C:/ruby/bin/cucumber:22:in `<top (required)>'

Running 'gem env' gives me...
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/ruby/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: H:/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: C:/ruby/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/ruby/bin
  - SPEC CACHE DIRECTORY: H:/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/ruby/lib/ruby/gems/2.3.0
     - H:/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - H:\bin
     - C:\ruby\Git\mingw64\bin
     - C:\ruby\Git\usr\local\bin
     - C:\ruby\Git\usr\bin
     - C:\ruby\Git\usr\bin
     - C:\ruby\Git\mingw64\bin
     - C:\ruby\Git\usr\bin
     - H:\bin
     - C:\ProgramData\Oracle\Java\javapath
     - C:\Program Files (x86)\Intel\iCLS Client
     - C:\Program Files\Intel\iCLS Client
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0
     - C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files\Intel\WiFi\bin
     - C:\Program Files\Common Files\Intel\WirelessCommon
     - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0
     - C:\Program Files (x86)\Skype\Phone
     - C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio
     - C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn
     - C:\Program Files\Microsoft SQL Server\110\Tools\Binn
     - C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn
     - C:\Users\stephenla.CW0DOMAIN\Downloads\phantomjs-2.1.1-windows\bin
     - C:\workspace\chrome_driver
     - C:\Users\stephenla.CW0DOMAIN\AppData\Local\apache-jmeter-3.0\bin
     - C:\gecko_driver
     - C:\ruby
     - C:\ruby\bin
     - C:\ruby\bin
     - C:\ruby2.1.8\Ruby2.2.0\bin
     - C:\ProgramData\Oracle\Java\javapath
     - C:\Program Files (x86)\Intel\iCLS Client
     - C:\Program Files\Intel\iCLS Client
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0
     - C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files\Intel\WiFi\bin
     - C:\Program Files\Common Files\Intel\WirelessCommon
     - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0
     - C:\Program Files (x86)\Skype\Phone
     - C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio
     - C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn
     - C:\Program Files\Microsoft SQL Server\110\Tools\Binn
     - C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn
     - C:\ruby\Git\cmd
     - C:\ruby\Git\usr\bin\vendor_perl
     - C:\ruby\Git\usr\bin\core_perl

What do I need to do to remove this requirement for cucumber 1.3.20?

**Comment by enkessler** [comment]
Are you using Bundler at all? That's usually the thing that is demanding that a specific version of a gem has to be used. Alternatively, you might be using a gem that declares itself to be incompatible with other versions of the cucumber gem.

**Comment by stevelake** [comment]
Closing this issue as solved: the UncaughtException was thrown when running tests from our RubyMine IDE (which was due to a different reason and how been resolved). The tests run fine from the command line. Many thanks for your assistance!
