### ISSUE TITLE
Build gherkin/dart

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin#24]
The new gherkin/dart module is not built in CI.

When https://github.com/cucumber/common/pull/1630 was merged we forgot to add a job to `.circleci/config.yml`, so it isn't built as a separate job. There is nothing in `gherkin/Makefile` either, so the module isn't built as part of the serial job either.

/cc @mattwynne @aurelien-reeves

**Comment by mpkorstanje** [comment]
Resolved by https://github.com/cucumber/gherkin/pull/3
