### ISSUE TITLE
Perl: Implement CLI

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin#242]
This issue is for remaining work of #240 related to Perl:

* [ ] Print errors as ndjson
* [ ] Replace `bin/gherkin-generate-ast` and `bin/gherkin-generate-pickles` with a new `bin/gherkin`
* [ ] Implement stream API

@pjlsergeant - want to help?

**Comment by pjlsergeant** [comment]
Sure, I'll get this done

**Comment by pjlsergeant** [comment]
I am on holiday last two weeks of December, and I'll get it done then.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#144
