### ISSUE TITLE
Go: Implement CLI

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin#245]
This issue is for remaining work of #240 related to Go:

* [ ] Print errors as ndjson
* [ ] Replace `bin/gherkin-generate-ast` with a new `bin/gherkin`
* [ ] Implement stream API
* [ ] Implement a pickles compiler and use it in stream API and `bin/gherkin`

@muhqu / @koterpillar / @l3pp4rd - any takers?

**Comment by koterpillar** [comment]
I don't have any Go expertise, sorry.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#145
