### ISSUE TITLE
Is It Possible Get Tag Line Position Of A GherkinDocument Generated From AstBuilder

### ISSUE THREAD

**Issue by bhreinb** [cucumber/gherkin#253]
Hi There,

I have the following code block that takes in a Gherkin Feature File which gets parsed as a GherkinDocument.

```java
Gson gson = new Gson();

JsonParser jsonParser = new JsonParser();

TokenMatcher matcher = new TokenMatcher();

Parser<GherkinDocument> parser = new Parser<>(new AstBuilder());

GherkinDocument gherkinDocument = null;

try {

    gherkinDocument = parser.parse(new InputStreamReader(new FileInputStream(fPath), "UTF-8"), matcher);

    System.out.println(gherkinDocument);

}
catch (UnsupportedEncodingException | FileNotFoundException e)
{

// TODO Auto-generated catch block
e.printStackTrace();

}

JsonObject jsonObject = (JsonObject) jsonParser.parse(gson.toJson(gherkinDocument));

for (int i = 0; i < gherkinDocument.getFeature().getChildren().size(); i++ )
{

    System.out.println(gherkinDocument.getFeature().getChildren().get(i).getClass());

    System.out.println(gherkinDocument.getFeature().getChildren().get(i).getName());

    System.out.println(gherkinDocument.getFeature().getChildren().get(i).getDescription());

    System.out.println(gherkinDocument.getFeature().getChildren().get(i).getKeyword());

}
```

However I'd like to know the line location of a Tag applicable to a scenario or scenario outline? Not the location of where a scenario or scenario outline occurs in the file.

Is it possible to get this at present? I'm using the following edition of Gherkin

        
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>gherkin</artifactId>
            <version>4.0.0</version>
        </dependency>

Many thanks in advance.

**Comment by enkessler** [comment]
The source line of a tag should be available in the AST that is generated by the parser.

Check out this feature file and its corresponding AST:
https://github.com/cucumber/gherkin/blob/v4.0.0/testdata/good/tags.feature
https://github.com/cucumber/gherkin/blob/v4.0.0/testdata/good/tags.feature.ast.json

**Comment by bhreinb** [comment]
Yeah fair point but that means I'd have to use JSON to get that information ie parse from gherkindocument to Json

Is it not possible to get ditectly via GherkinDocument i.e.

gherkinDocument.getFeature().getChildren().get(i)

**Comment by aslakhellesoy** [comment]
Try this:

```java
    @Test
    public void can_get_tag_from_scenarios() {
        Parser<GherkinDocument> parser = new Parser<>(new AstBuilder());

        GherkinDocument gherkinDocument = parser.parse(new StringReader("Feature: Hungry\n" +
                "  @freaks\n" +
                "  Scenario: daddy\n" +
                "    Given I ain't got no heart\n" +
                "\n" +
                "  @who\n" +
                "  Scenario Outline: Are\n" +
                "    Given the brain police\n" +
                "    "));


        List<Tag> tags = new ArrayList<>();
        for (ScenarioDefinition scenarioDefinition : gherkinDocument.getFeature().getChildren()) {
            if (scenarioDefinition instanceof Scenario) {
                // You have to cast. Sue me.
                tags.addAll(((Scenario) scenarioDefinition).getTags());
            } else if (scenarioDefinition instanceof ScenarioOutline) {
                tags.addAll(((ScenarioOutline) scenarioDefinition).getTags());
            }
        }
        assertEquals("@freaks", tags.get(0).getName());
        assertEquals(2, tags.get(0).getLocation().getLine());
        assertEquals(3, tags.get(0).getLocation().getColumn());
    }
```

This example is written against `master`. I believe it should work against 4.0.0 too.

Are you building a custom reporter or something else? Depending on what you're trying to accomplish there may be a more efficient/useful/thorough way to do this, using the compiler:

```java
    @Test
    public void can_get_tag_from_pickles() {
        Parser<GherkinDocument> parser = new Parser<>(new AstBuilder());

        GherkinDocument gherkinDocument = parser.parse(new StringReader("@zappa\n" +
                "Feature: Hungry\n" +
                "  @freaks\n" +
                "  Scenario: daddy\n" +
                "    Given I ain't got no heart\n" +
                "\n" +
                "  @who\n" +
                "  Scenario Outline: Are\n" +
                "    Given the brain <police>\n" +
                "    \n" +
                "    Examples:\n" +
                "      | police |\n" +
                "      | Go     |\n" +
                "      | Cry    |\n" +
                "      | On     |\n" +
                "      "));

        List<Pickle> pickles = new Compiler().compile(gherkinDocument);
        Pickle cry = pickles.get(3);
        List<PickleTag> tags = cry.getTags();
        assertEquals("@zappa", tags.get(0).getName());
        assertEquals("@who", tags.get(1).getName());
        assertEquals(15, cry.getLocations().get(0).getLine());
    }
```

**Comment by aslakhellesoy** [comment]
Closing this since it's "fixed" (answered the question).

Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by bhreinb** [comment]
Hey @aslakhellesoy 

No problem and many thanks a mill for the sample code. That solves my issue for me. The pickles sample that you sent doesn't work with 4.0.0. I'm assuming this works on master. I see 4.0.0 was released 10 months ago approximately. When will the next release occur of Gherkin and how frequently do you release?

**Comment by aslakhellesoy** [comment]
The release cadence is not regular. It depends on the needs of downstream dependencies (Cucumber mainly) and how much time the core team has available.

I hope the next release will be released "soon", that's all I can say.
