### ISSUE TITLE
cannot load such file -- 2.2/gherkin_lexer_en

### ISSUE THREAD

**Issue by ChinmoyJana14** [cucumber/gherkin#259]
Also tried with uninstalling gherkin and again installing.
Getting the below Error while try to run feature file from ruby mine:
LANGUAGE LOCALE en_XX
WARNING: cannot load such file -- 2.2/gherkin_lexer_en
Couldn't load 2.2/gherkin_lexer_en
The $LOAD_PATH was:
lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-1.3.20/bin/../lib
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/bdd
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/testunit
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/bdd
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/builder-3.2.3/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/diff-lcs-1.3/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/multi_json-1.12.1/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/gherkin-2.12.2
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/gherkin-2.12.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/multi_test-0.1.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-1.3.20/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/json-1.8.6
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.6/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/slowhandcuke-0.0.3/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubyzip-1.2.1/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/awesome_print-1.7.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httpclient-2.8.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/escape-0.0.4/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/luffa-2.0.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/unicode-0.4.4.2
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/unicode-0.4.4.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mini_portile2-2.1.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.0.1-x64-mingw32/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubyXL-3.3.23/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/minitest-5.10.1/lib
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/x64-msvcrt
C:/Ruby22-x64/lib/ruby/site_ruby
C:/Ruby22-x64/lib/ruby/vendor_ruby/2.2.0
C:/Ruby22-x64/lib/ruby/vendor_ruby/2.2.0/x64-msvcrt
C:/Ruby22-x64/lib/ruby/vendor_ruby
C:/Ruby22-x64/lib/ruby/2.2.0
C:/Ruby22-x64/lib/ruby/2.2.0/x64-mingw32. Reverting to Ruby lexer.
WARNING: cannot load such file -- 2.2/gherkin_lexer_en
Couldn't load 2.2/gherkin_lexer_en
The $LOAD_PATH was:
lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-1.3.20/bin/../lib
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/bdd
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/testunit
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/bdd
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/builder-3.2.3/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/diff-lcs-1.3/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/multi_json-1.12.1/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/gherkin-2.12.2
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/gherkin-2.12.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/multi_test-0.1.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-1.3.20/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/json-1.8.6
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.6/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/slowhandcuke-0.0.3/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubyzip-1.2.1/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/awesome_print-1.7.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httpclient-2.8.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/escape-0.0.4/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/luffa-2.0.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/unicode-0.4.4.2
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/unicode-0.4.4.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mini_portile2-2.1.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.0.1-x64-mingw32/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubyXL-3.3.23/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/minitest-5.10.1/lib
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/x64-msvcrt
C:/Ruby22-x64/lib/ruby/site_ruby
C:/Ruby22-x64/lib/ruby/vendor_ruby/2.2.0
C:/Ruby22-x64/lib/ruby/vendor_ruby/2.2.0/x64-msvcrt
C:/Ruby22-x64/lib/ruby/vendor_ruby
C:/Ruby22-x64/lib/ruby/2.2.0
C:/Ruby22-x64/lib/ruby/2.2.0/x64-mingw32. Reverting to Ruby lexer.
WARNING: cannot load such file -- 2.2/gherkin_lexer_en
Couldn't load 2.2/gherkin_lexer_en
The $LOAD_PATH was:
lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-1.3.20/bin/../lib
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/bdd
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/testunit
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/common
C:/Program Files (x86)/JetBrains/RubyMine 7.0.4/rb/testing/patch/bdd
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/builder-3.2.3/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/diff-lcs-1.3/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/multi_json-1.12.1/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/gherkin-2.12.2
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/gherkin-2.12.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/multi_test-0.1.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-1.3.20/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/json-1.8.6
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.6/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/slowhandcuke-0.0.3/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubyzip-1.2.1/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/awesome_print-1.7.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httpclient-2.8.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/escape-0.0.4/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/luffa-2.0.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/unicode-0.4.4.2
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/unicode-0.4.4.2/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mini_portile2-2.1.0/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.0.1-x64-mingw32/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubyXL-3.3.23/lib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/minitest-5.10.1/lib
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0
C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/x64-msvcrt
C:/Ruby22-x64/lib/ruby/site_ruby
C:/Ruby22-x64/lib/ruby/vendor_ruby/2.2.0
C:/Ruby22-x64/lib/ruby/vendor_ruby/2.2.0/x64-msvcrt
C:/Ruby22-x64/lib/ruby/vendor_ruby
C:/Ruby22-x64/lib/ruby/2.2.0
C:/Ruby22-x64/lib/ruby/2.2.0/x64-mingw32. Reverting to Ruby lexer.

**Comment by enkessler** [comment]
You appear to be using an old version of Cucumber (1.3.2) which is limited to the 2.x versions of the Gherkin gem. You also appear to be using Gherkin 2.x on Windows with Ruby 2.x. While the 2.x series of the gherkin gem will work with Ruby 2.x on Windows (that is to say, you are seeing all of that stack trace looking noise but whatever you are doing will still happen successfully), Ruby 2.x on Windows was not fully supported until gherkin 3.x and later.

If you upgrade your Cucumber/Gherkin to a newer version, the noise should go away.

**Comment by ChinmoyJana14** [comment]
I will try by upgrading the Cucumber version
