### ISSUE TITLE
Duplicate scenario keyword in sr-Cyrl language

### ISSUE THREAD

**Issue by ccrighton** [cucumber/gherkin#263]
### 👓 What did you see?

In [gherkin-languages.json](https://github.com/cucumber/gherkin/blob/main/gherkin-languages.json) the sr-Cyrl language definition has a duplicate value in the scenario section.  Items 1 and 3 are the same.

```
    "scenario": [
      "Пример",
      "Сценарио",
      "Пример"
    ],

```

### ✅ What did you expect to see?

No duplicates e.g.:

```
    "scenario": [
      "Пример",
      "Сценарио"
    ],

```

### 📦 Which tool/library version are you using?

[9c90236](https://github.com/cucumber/gherkin/commit/9c90236640b0b364e97cc85d342b4791687e6108)

**Comment by mpkorstanje** [comment]
Cheers! Fixed.
