### ISSUE TITLE
WARNING: cannot load such file -- 2.0/gherkin_lexer_en（win7+ruby 2.0.0+gherkin 2.12.1 ）

### ISSUE THREAD

**Issue by ouguangqian** [cucumber/gherkin#273]
Hello I am workin in windows 7 64bit with ruby 2.0.0p247 (2013-06-27) [x64-mingw32] and gherkin 2.12.1 and it doesn't work fine when I try to use it, I always have the same message:

WARNING: cannot load such file -- 2.0/gherkin_lexer_en
Couldn't load 2.0/gherkin_lexer_en
The $LOAD_PATH was:
lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/bin/../lib
D:/Program Files (x86)/JetBrains/RubyMine 5.0/rb/testing/patch/common
D:/Program Files (x86)/JetBrains/RubyMine 5.0/rb/testing/patch/bdd
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/builder-3.2.2/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/diff-lcs-1.2.4/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/multi_json-1.8.0/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gherkin-2.12.1/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/multi_test-0.0.2/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.14.2/lib
D:/Ruby200-x64/lib/ruby/site_ruby/2.0.0
D:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/x64-msvcrt
D:/Ruby200-x64/lib/ruby/site_ruby
D:/Ruby200-x64/lib/ruby/vendor_ruby/2.0.0
D:/Ruby200-x64/lib/ruby/vendor_ruby/2.0.0/x64-msvcrt
D:/Ruby200-x64/lib/ruby/vendor_ruby
D:/Ruby200-x64/lib/ruby/2.0.0
D:/Ruby200-x64/lib/ruby/2.0.0/x64-mingw32. Reverting to Ruby lexer.
WARNING: cannot load such file -- 2.0/gherkin_lexer_en
Couldn't load 2.0/gherkin_lexer_en
The $LOAD_PATH was:
lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/bin/../lib
D:/Program Files (x86)/JetBrains/RubyMine 5.0/rb/testing/patch/common
D:/Program Files (x86)/JetBrains/RubyMine 5.0/rb/testing/patch/bdd
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/builder-3.2.2/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/diff-lcs-1.2.4/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/multi_json-1.8.0/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gherkin-2.12.1/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/multi_test-0.0.2/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.14.2/lib
D:/Ruby200-x64/lib/ruby/site_ruby/2.0.0
D:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/x64-msvcrt
D:/Ruby200-x64/lib/ruby/site_ruby
D:/Ruby200-x64/lib/ruby/vendor_ruby/2.0.0
D:/Ruby200-x64/lib/ruby/vendor_ruby/2.0.0/x64-msvcrt
D:/Ruby200-x64/lib/ruby/vendor_ruby
D:/Ruby200-x64/lib/ruby/2.0.0
D:/Ruby200-x64/lib/ruby/2.0.0/x64-mingw32. Reverting to Ruby lexer.
wrong number of arguments (1 for 0) (ArgumentError)
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/location.rb:22:in `file_colon_line'
D:/Program Files (x86)/JetBrains/RubyMine 5.0/rb/testing/patch/bdd/teamcity/cucumber/common.rb:126:in `tc_before_feature'
D:/Program Files (x86)/JetBrains/RubyMine 5.0/rb/testing/patch/bdd/teamcity/cucumber/formatter_03103.rb:46:in `before_feature'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/tree_walker.rb:181:in `block in send_to_all'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/tree_walker.rb:179:in `each'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/tree_walker.rb:179:in `send_to_all'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/tree_walker.rb:169:in `broadcast'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/tree_walker.rb:26:in `visit_feature'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/features.rb:28:in `block in accept'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/features.rb:17:in `each'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/features.rb:17:in `each'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/features.rb:27:in `accept'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/tree_walker.rb:21:in `block in visit_features'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/ast/tree_walker.rb:20:in `visit_features'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/runtime.rb:48:in `run!'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/lib/cucumber/cli/main.rb:47:in `execute!'
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cucumber-1.3.8/bin/cucumber:13:in `<top (required)>'
D:/Ruby200-x64/bin/cucumber:23:in `load'
D:/Ruby200-x64/bin/cucumber:23:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'

Process finished with exit code 1
Empty test suite.
Does anybody know the problem?
Thanks in advance

**Comment by wpride** [comment]
@mscharley thanks much!

**Comment by jnyman** [comment]
The fix by @mscharley does work but the problem I find is that if I have users on Windows simply do "gem install gherkin", they get the mingw32 version which seems to not work even with the fix proposed. If I make sure everyone uses "gem install gherkin --platform=ruby" then the fix proposed works. However, if someone runs a "bundle install" they usually get the mingw32 version loaded and, in those cases, neither fix works any more. Further, I then usually get a segmentation fault when attempting to "gem uninstall" gherkin.

This really does need to be fixed if there is a desire to have Cucumber be viable in the Windows world. I'm working with a series of consulting firms (that are in turn working with legal and health care firms), all using Windows. This lack of ability to just have Cucumber and Gherkin run has quite literally stopped them from adoption.

**Comment by kevinrood** [comment]
@jnyman would specifying the platform in your `Gemfile` help?

```ruby
gem 'gherkin', platforms: :ruby
```

Not an ideal solution I know.

As an aside, I ended up using JRuby to solve my problems related to running Ruby on Windows.

**Comment by mscharley** [comment]
@jnyman that is only because there's a mingw32 version of the gem pushed to the repositories currently. If this fix was adopted upstream this wouldn't be an actual issue.

@aslakhellesoy what's the status of this issue? It's been swimming around for a while now.

**Comment by mattwynne** [comment]
We're actively working on a new Gherkin parser: https://github.com/cucumber/gherkin3 which will replace this one. One of the main drivers of that re-write is that this one has become a major pain to build and release.

Realistically though, we're probably 6 months minimum away from having gherkin 3 integrated into Cucumber-Ruby and in production. I hate shutting Windows users out like this. I've experienced the same as you @jnyman on client site, and it's embarrassing.

Does anyone have the energy to try and get a new version of the gherkin gem built with the pure ruby parser in it? I'd happily release a new version of Cucumber that depends on it, and help that person get their build of gherkin released.

**Comment by tooky** [comment]
@mattwynne I have a windows vm now. Maybe we can sort something at cukeup?

**Comment by jnyman** [comment]
@tooky , @mattwynne - I have a ton of energy to help. My only problem is that I don't know if my skills would be up to the task. I have plenty of Windows machines that I could help test on, however. Further, I certainly don't mind working to level up my skills and contribute where I can.

**Comment by osteenbergen** [comment]
@mattwynne Did you (or anybody else) make any progress?

```
Does anyone have the energy to try and get a new version of the gherkin gem built with the pure ruby parser in it? I'd happily release a new version of Cucumber that depends on it, and help that person get their build of gherkin released
```
Do you mean a version of gherkin 2 with the gherkin3 parser in it, or a gem that by default uses platform=ruby? I could probably find some time to tinker with it

**Comment by weiserma** [comment]
Any resolution to this.  Just installed a new platform and still getting the cannot load file.   tried changing the prefix... didn't  help.

ruby 2.1.6p336 (2015-04-13 revision 50298) [i386-mingw32]

**Comment by kramerdog** [comment]
I ended up side-stepping this issue completely by doing all of my
development in a Ubuntu VM running on the Windows machine.

It makes much more sense to develop in the same environment as my target
deployment environment anyway.

Good luck.

**Comment by mattwynne** [comment]
Cucumber-Ruby v2.1 now uses the new Gherkin3 parser. Please give it a try!

**Comment by d-led** [comment]
superb, thanks!! v2.1 works
