### ISSUE TITLE
Python does not keep version in pyproject.toml

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/gherkin#289]
### 🤔 What's the problem you've observed?

[Releases are made with a script](https://github.com/cucumber/polyglot-release). This is necessary because nobody can remember the intricacies and conflicting requirements of releasing (currently) 13 different languages.

So for the sake of the sanity of everyone involved in the release there should be exactly one conventional location for every python project in the Cucumber org to keep its version.

Currently the preferred place is directly in pyproject.toml.

For Gherkin currently the version  is kept in `setup.py`.

https://github.com/cucumber/gherkin/blob/76333135e9a418d00d5fe0ff994262dae7dc5910/python/setup.py#L6

### ✨ Do you have a proposal for making it better?

Keep the version in `pyproject.toml`.

### 📚 Any additional context?

I am open to better ways of doing this, but then I'd like to see a set of merge requests apply that change to all repositories at once.

So for the short term it I'd be best to use `pyproject.toml`.

**Comment by youtux** [comment]
Done in https://github.com/cucumber/gherkin/pull/290

**Comment by jsa34** [comment]
Resolved in commit https://github.com/cucumber/gherkin/commit/24296c19083053b3c612b9c33a007e654a8fd657

**Comment by mpkorstanje** [comment]
Cheers!
