### ISSUE TITLE
*.razor files have executable permissions

### ISSUE THREAD

**Issue by jenisys** [cucumber/gherkin#291]
### 👓 What did you see?

When I clone this repository on a UNIX systems,
several or all `*.razor` files have executable permissions.

This is not necessary (IMHO) and probably an artefact that BERP grammar generation normally occurs on Windows (or in the container).

EXAMPLES:

* `javascript/gherkin-javascript.razor`
* `python/gherkin-python.razor`
* ...

### ✅ What did you expect to see?

The `*.razor` should not have executable permissions (best verified on a UNIX system, like: macOS, Linux, BSD, Windows WSL, ...).

### 📦 Which tool/library version are you using?

NOT RELEVANT, because this a development/maintenance issue of the Git repository.

### 🔬 How could we reproduce it?

On a UNIX system:

```bash
# -- USE: bash shell (or some other shell)
$ git clone https://github.com/cucumber/gherkin.git
$ cd gherkin
$ ls -laF javascript/*.razor
-rwxr-xr-x  $SOME_USER  $SOME_GROUP  $FILE_SIZE $FILE_DATE javascript/gherkin-javascript.razor*
```

**Comment by mpkorstanje** [comment]
I have no idea why these are executable either. 

Feel free to make pull request. If it changes exactly this, it will be quick to merge.
