### ISSUE TITLE
Gherkin => AST => Gherkin printer?

### ISSUE THREAD

**Issue by samccone** [cucumber/gherkin#31]
I was wondering if this was something you guys were interested in.

I would be useful for performing batch operations across a code base, like tagging every n'th scenario or changing a word everywhere in a code base.

thoughts?

**Comment by mattwynne** [comment]
Sounds like a great idea to me. One thing to consider is that much of the time we'll want to be able to also de-compile test-cases into an AST for printing too, but I think that could be considered a separate issue.

**Comment by aslakhellesoy** [comment]
@samccone are you thinking about some kind of library with plugins for rewriting the source? Did you have a particular programming language in mind?

What's the use case for tagging every n'th scenario? Changing a word is for refactoring, right? Are you thinking of a command-line tool?

Personally I think a standalone pretty-printer would be nice.

**Comment by samccone** [comment]
Hey @mattwynne and @aslakhellesoy 

Here is my use case

I have a test suite with a few thousand scenarios, I would like to be able to run them across a grid of boxes. I would like to be able to something like...

```bash
split-tests features/**/*.feature --index=2 --total=10 &&
run-tests
```
---

Is this a niche use case? I think not but you guys would be more expert in this area than I.

While I think being able to do a full circle with the source code => AST => source code is a super powerful thing and concept, I think having a plugin that sat on top of one of the parsers would also work.

Let me know

**Comment by aslakhellesoy** [comment]
Running scenarios across a grid of boxes is definitely not a niche use case - lots of people want to do that!

None of the Cucumber implementations have native support for this, but there are many 3rd party tools that support it. I think it would be great to support natively.

I'm not sure Gherkin->AST->Gherkin is the best abstraction level to handle that though. The [compiler](https://github.com/cucumber/gherkin3/blob/master/README.md#compiler) we're working on will produce "compiled" scenarios from Gherkin (and possibly other formats), and I think this is what should be split across a grid. Doing at this level means we can leverage the same architecture for other input formats such as Markdown.

The kind of "dynamic tagging" you're mentioning can be done entirely in memory (compiled scenarios have tags too).

I'm not sure I see any other uses of Gherkin->AST->Gherkin than pretty printing.

Thoughts?

**Comment by mattwynne** [comment]
You're right Aslak that distributing load would work better at the test-case level. It would be quite similar to [the randomizer](https://github.com/cucumber/cucumber/blob/master/lib/cucumber/filters/randomizer.rb)

I have an intuitive desire for this feature though. I wonder what that's based on?

**Comment by samccone** [comment]
> distributing load would work better at the test-case level

Sure that is what I am currently doing :smile: 

I think adding a "printer" that takes the AST object and outputs gherkin would be quite swell. It opens the door for some interesting things to happen.

I am going to just list a few naive examples that came to the top of my head

* JIT filtering of tests on CI (based on a stop being used on a feature)
* Building an AST outside of the parser and using this tool to output gherkin 
* (As I mentioned before) Batch tagging or mutation across gherkin files
* Programmatic introspection into your gherkin files to recommend fixes
  * Think https://houndci.com/
  * Think jscs or jshint... but for gherkin


:)

**Comment by aslakhellesoy** [comment]
I think all of these ideas are great ideas.

What I propose is a pull-based approach: Start by building the software that needs the AST->Gherkin conversion, and let that drive out what it needs to look like, rather than the other way around.

WDYT?

**Comment by enkessler** [comment]
This thread is wonderful. My only regret is not finding it sooner.

I have made tools that can do these things:
https://github.com/enkessler/cuke_modeler

**Comment by paroxyzm** [comment]
This tool would be ideal for my use case! Just started looking around... Has anyone been successful with implementing code => AST => code tool? If not I would gladly participate

**Comment by aslakhellesoy** [comment]
Here is how it should work I think:

    bin/gherkin-generate-ast < my.feature > my.json
    ast2gherkin < my.json > my-roundtripped.feature
    diff my.feature my-roundtripped.feature # no difference

It would be great if this were a standalone command line tool that could be easily built and distributed for any platform. I think `go` is the best language for that. Binaries are small and self-contained and can be built for Linux, Windows, OSX with ease.

We have some decent testdata for this tool in `/testdata/good` too!

Any takers?

**Comment by aslakhellesoy** [comment]
I don't think you meant to close this @mattwynne (?)

**Comment by mattwynne** [comment]
No, I didn’t - sorry!

> On 25 Feb 2016, at 16:58, Aslak Hellesøy <notifications@github.com> wrote:
> I don't think you meant to close this @mattwynne <https://github.com/mattwynne> (?)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/cucumber/gherkin/issues/31#issuecomment-188877630>.

-- 



The Cucumber logo is the intellectual property of Cucumber Ltd, a limited 
company registered in Scotland, number 456793.

UK Headquarters: Cucumber Ltd, Drumsyniebeg, Lochgoilhead, Cairndow, 
Argyll, PA24 8AN UK.

CONFIDENTIALITY NOTICE: The information in this e-mail is confidential and 
privileged; it is intended for use solely by the individual or entity named 
as the recipient hereof. Disclosure, copying, distribution, or use of the 
contents of this e-mail by persons other than the intended recipient is 
strictly prohibited and may violate applicable laws. If you have received 
this e-mail in error, please delete the original message and notify us by 
email immediately. Thank you. Cucumber Ltd.

**Comment by enkessler** [comment]
How close of a file diff are you shooting for? Does the AST really capture everything EXACTLY? I want to say that there is some whitespace lost. At least, it seemed like that was the case when I had to update all of the tests for my current gherkin -> AST -> gherkin tool.

**Comment by aslakhellesoy** [comment]
The AST does not capture insignificant whitespace, so we can ignore this in the comparisons.

I suggest removing empty lines and trimming the remaining ones before doing a diff.

We can eyeball that the output "looks good".

Formatting rules are roughly:
* 2 space indent for child nodes
* 1 line of space above each feature child
* Align table cells

**Comment by enkessler** [comment]
Fair enough.

Elephant in the room: why add this functionality to this gem? As opposed to utilizing some third-party tool?

**Comment by aslakhellesoy** [comment]
I don't think we should add this functionality to this project. I think it should be a separate project, written only in go (for portability reasons).

What third-party tool are you referring to?

**Comment by enkessler** [comment]
[cuke_modeler](https://github.com/enkessler/cuke_modeler) and its [friends](https://rubygems.org/profiles/enkessler). I may have [mentioned](https://groups.google.com/forum/#!topic/cukes/x9W30eFWInQ) them [a](https://groups.google.com/forum/#!topic/cukes/gq1F7Tmd3Dk) [few](https://github.com/cucumber/gherkin/issues/109) [times](https://groups.google.com/forum/#!topic/cukes/mZ4abEyRbdg). O:)
