### ISSUE TITLE
perl: Acceptance tests do not include parse errors

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/gherkin#31]
### 🤔 What's the problem you've observed?

Currently the error set of tokens is not included in the acceptance tests.

https://github.com/cucumber/gherkin/blob/1cc2ef0153603c5e51818b59ff6d632238491226/perl/Makefile#L46

This is a problem because:

> As of May 2016 Gherkin is implemented in 8 languages. This number is likely to increase to a dozen within a year or two. Very few programmers are intimate with all those languages. Therefore, in order to make it as easy as possible to refactor, fix bugs, add features and release packages it is essential that all implementations have a similar structure.

_[CONTRIBUTING.md - consistency between implementations](https://github.com/cucumber/gherkin/blob/main/CONTRIBUTING.md#consistency-between-implementations)_

### ✨ Do you have a proposal for making it better?

Fix the acceptance tests to include the parse errors.

**Comment by ehuelsmann** [comment]
yep. I'll have a look in the morning.

**Comment by mpkorstanje** [comment]
Cheers! No rush at all, it's been like this for a while.
