### ISSUE TITLE
GherkinParser loses backslashes from the data table values

### ISSUE THREAD

**Issue by FedorGabrus** [cucumber/gherkin#335]
### 👓 What did you see?

Step definition with a data table in the feature file:

```
Given I use my step defintion
| 1 \ | 2 \\ | 3 \\\ | 4 \\\\ | 5 \\\\\ |
```

I use the following to parse the feature file and get GherkinDocument:
```
GherkinParser.builder().build()
.parse(featureFilePath)
.filter(envelope -> envelope.getGherkinDocument().isPresent())
.map(envelope -> envelope.getGherkinDocument().get()).findFirst()
.orElseThrow(() -> ...)
```

GherkinParser loses backslashes from the data tabe:
(For convenience, I'll show output without escaping chars where each `\` represents one backslash).
Parsed values:

1. `1 \`
2. `2 \`
3. `3 \\`
4. `4 \\`
5. `5 \\\`

### ✅ What did you expect to see?

Same, \ shown without escaping:

1. `1 \`
2. `2 \\`
3. `3 \\\`
4. `4 \\\\`
5. `5 \\\\\`

### 📦 Which tool/library version are you using?

Java 21
gherkin 30.0.4
cucumber-core 7.20.1
cucumber-java 7.20.1

### 🔬 How could we reproduce it?

1. Create a feature file that has a step definition with a data table containing multiple backslashes in a cell:
```
@my_feature
Feature: multiple backslash issue

    Scenario: my_scenario
    Given I use my step defintion
    | 1 \ | 2 \\ | 3 \\\ | 4 \\\\ | 5 \\\\\ |
```
2. Parse feature file and get cells values:
```
Path pathToFeatureFile = ...
GherkinDocument document = GherkinParser.builder().build()
        .parse(pathToFeatureFile )
        .filter(envelope -> envelope.getGherkinDocument().isPresent())
        .map(envelope -> envelope.getGherkinDocument().get()).findFirst()
        .get();
List<String> values = document .getFeature().get()
        .getChildren().getFirst()
        .getScenario().get()
        .getSteps().getFirst()
        .getDataTable().get()
        .getRows().getFirst()
        .getCells().stream()
        .map(TableCell::getValue)
        .toList();
```

**Comment by mpkorstanje** [comment]
This currently is a feature not a bug.

https://github.com/cucumber/gherkin/blob/00fcc43f56ca69c6dbd68e85a41129a0f3b6b915/testdata/good/escaped_pipes.feature#L2-L3

The alternative would be a parse error when an odd number of `\` is used.

**Comment by FedorGabrus** [comment]
I would agree but on the test runtime it treats it as it is not escaped.

**Comment by FedorGabrus** [comment]
I would agree if test runtime treated it the same way.
So I have \\\ in the data table, parser shows me \\ and on the test execution cucumber treats it as \\\
