### ISSUE TITLE
Scenerios should be randomized across feature files, not just within a feature file

### ISSUE THREAD

**Issue by fakeleft** [cucumber/gherkin#337]
... or at least is seems to me that this would be a more thorough way of catching state dependencies between scenarios...

**Comment by aslakhellesoy** [comment]
Completely agree. This should go into individual cucumber implementations though, not the parser. Feel free to open a new ticket in the repo for one of the cucumber implementations.

**Comment by mattwynne** [comment]
Cucumber-Ruby does this as of version 2.0
