### ISSUE TITLE
php: Parser is not generated with the right formatting

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/gherkin#35]
### 🤔 What's the problem you've observed?

One of the goals of setting up the workflow for this project was that generating parsers should only depend on Berp. This simplifies the image needed to build this project. However PHP also formatted the parser using vendored tools. This effectively adds a dependency on PHP. 

https://github.com/cucumber/gherkin/blob/6b84ba8e92c901192c707ac66ee61695cbf1b9f3/php/Makefile#L47-L52

### ✨ Do you have a proposal for making it better?

Either
 * fix `gherkin-php.razor` to produce correctly formatted files
 * or ignore the problem. It is generated code.

### :computer: Additional context

In https://github.com/cucumber/gherkin/pull/3 I've removed the code formatter and fixed most of the razor file. I couldn't fix everything.

**Comment by mpkorstanje** [comment]
@ciaranmcnulty what do you think?

**Comment by ciaranmcnulty** [comment]
Yeah I agree this should be changed. Probably this was just laziness understanding the berp templates on my part.

It makes sense to me, now that we're unpicking the build steps, to have the codegen here rely only on Berp, but validate the formatting as part of the PHP test run by using `php-cs-fixer` with appropriate flags to not 'fix' stuff.

I made a similar change in the [Messages buildkit spike thingy](https://github.com/cucumber/messages/pull/58)

IIRC the Golang build does `go fmt` during code generation, so maybe we should change it there too.

**Comment by mpkorstanje** [comment]
> IIRC the Golang build does go fmt during code generation, so maybe we should change it there too.

Already fixed that. 

> It makes sense to me, now that we're unpicking the build steps, to have the codegen here rely only on Berp, but validate the formatting as part of the PHP test run by using php-cs-fixer with appropriate flags to not 'fix' stuff.

Makes sense.
