### ISSUE TITLE
perl: CPAN_USER and CPAN_PASSWORD are not stored in Keybase

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/gherkin#42]
### 🤔 What's the problem you've observed?

The core team has agreed to keep all secrets in keybase.

Currently `CPAN_USER` and `CPAN_PASSWORD` are not present. 

@mattwynne @ehuelsmann do you know where they are?

**Comment by mpkorstanje** [comment]
Revert ecc7733 once located.

**Comment by ehuelsmann** [comment]
They are not? They used to be.

**Comment by mpkorstanje** [comment]
I've found them in the git history. Looks like a merge conflict got resolved poorly.

**Comment by mpkorstanje** [comment]
Secrets restored in keybase.
