### ISSUE TITLE
Multiline in examples tables

### ISSUE THREAD

**Issue by thr0w** [cucumber/gherkin#52]
``` gherkin
Scenario: [case]
    Given I need to transpile
    When EcmaScript6=[EcmaScript6]
    Then EcmaScript5=[EcmaScript5]

Examples:
  case             | EcmaScript6              | EcmaScript5
  --------------------------------------------------------------------------------
  arrow function   | var r=arr.map((x)=>x*x); | "use strict";
                   |                          |
                   |                          | var r=arr.map(
                   |                          |   function(x){
                   |                          |     return x*x;
                   |                          | });
  --------------------------------------------------------------------------------
  template strings | var s=`x=${x}            | var s='x='.concat(x).concat('\n')
                   | y=${y}`;                 | .concat('y=').concat(y);
```

Why: 
- It's very useful
- Simple to parse, just use a blank or a dashed line before each example.

Note:
- Identation it's important
- Allow one or more empty lines between rows for pretty code
- Sample working [here](https://github.com/thr0w/yadda/blob/master/test/features/multiline_example_scenarios.feature)

**Comment by aslakhellesoy** [comment]
Cucumber and Gherkin is designed to bridge the communication gap between non-technical and technical people by providing a syntax that is easy for non-technical people to learn.

It seems you want to use it more as a scripting tool. Adding code to Gherkin is not a good example of how it is intended to be used. No non-technical person would understand this.

It's the first time I've come across this feature request, so I'm not convinced it's something that more people would find useful - especially not non-technical people.

**Comment by mattwynne** [comment]
I disagree Aslak - I think this is a really cool use of Cucumber. We want to use it to write executable specifications - why not executable specifications of technical tools too?

I also like the way the tables look without the preceding column separator.

**Comment by thr0w** [comment]
@aslakhellesoy, I sorry about disagree and and sorry too about my poor examples. I'm not a Gherkins founder and I'm learning it now. But, would be very nice if we can use it too in more complicated things, like transpiling, systems integration, text conversions, etc. 

I don't wanna a scripting tool, sorry again about my examples. But it's my business work with complex data internally, with vendors and with customers.


@mattwynne , I work with medical systems. Often I need integrate with machine or systems others vendors. Below is a real sample.


```gherkin
Scenario: HL7 Clinical Chemistry Integration
   Given a LIS integrated by HL7
   When LIS recieve [message]
   Then LIS must emit a [report]

Examples:
   message                                                                   ┆ report
   ----------------------------------------------------------------------------------------------------
   PID|1|1034157|012993817||SNOW^JOHN||19520101|M|||1234 MAIN^^DEARBORN      ┆ JOHN SNOW, Male, 63 years
   OBX|2|NM|2093-3^CHOLESTEROL^LOINC|138.000|MG/DL|100.000 - 200.000|N|||F|  ┆ Cholesterol 138 mg/dl
```

**Comment by riaan53** [comment]
+1

**Comment by aslakhellesoy** [comment]
I'd be happy to consider a pull request for this. No amount of +1 will persuade me to do it for you though ;-)

**Comment by jenisys** [comment]
Mmh, for me it easier to read if you would put the different cases into 2 scenarios where the when/then steps have text parts. I think that is much easier to read (and understand) than long multiline rows in table (especially in your example).
