### ISSUE TITLE
Support | (\u007C) or ┆ (\u2506) as column separator.

### ISSUE THREAD

**Issue by thr0w** [cucumber/gherkin#54]
``` gherkin
Scenario: [nth]
   Given [nth]
   When [char]
   Then [name] 

Examples:
    nth    ┆ char ┆ name
    First  ┆  -   ┆ dash
    Second ┆  |   ┆ pipe
```

Why:
- It's important when | (\u007C)  is part of data and it's pretty than escaping (|)
- Simple to parse: if line has ┆(\u2506) use it else use | (\u007C)  as column separator

**Comment by aslakhellesoy** [comment]
The `|` character isn't used frequently in anything else than code.

Gherkin is not a language that is designed to embed code - it's designed to be used with human language.

Adding another separator to make it easier to use `|` in cell values sends a signal that we want to make it easier for people to embed code in Gherkin. That's the opposite of what we want people to do, so I'm not keen on adding this. I think escaping is sufficient. It's ugly, but that's good. If you're compelled to use `|` in cell values you're probably doing something wrong.

**Comment by mattwynne** [comment]
I would like to see a real-world example where this would be useful.

**Comment by thr0w** [comment]
@aslakhellesoy, I sorry about disagree and and sorry too about my poor examples. I'm not a Gherkins founder and I'm learning it now. But, would be very nice if we can use it too in more complicated things, like transpiling, systems integration, text conversions, etc. 

I don't wanna a scripting tool, sorry again about my examples. But it's my business work with complex data internally, with vendors and with customers.


@mattwynne , I work with medical systems. Often I need integrate with machine systems others vendors. Below is a real sample.


```gherkin
Scenario: HL7 Clinical Chemistry Integration
   Given a LIS integrated by HL7
   When LIS recieve [message]
   Then LIS must emit a [report]

Examples:
   message                                                                   ┆ report
   ----------------------------------------------------------------------------------------------------
   PID|1|1034157|012993817||SNOW^JOHN||19520101|M|||1234 MAIN^^DEARBORN      ┆ JOHN SNOW, Male, 63 years
   OBX|2|NM|2093-3^CHOLESTEROL^LOINC|138.000|MG/DL|100.000 - 200.000|N|||F|  ┆ Cholesterol 138 mg/dl
```

**Comment by aslakhellesoy** [comment]
Thanks for the real-world example @thr0w - that makes a lot more sense now. I'm reopening this.
