### ISSUE TITLE
Release go package

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin#59]
Should we use http://labix.org/gopkg.in for releases? As far as I understand, using this would allow us to keep the https://github.com/cucumber/gherkin-go repo for multiple releases, using regular git tags.

We also need a "Making a release" section in go/CONTRIBUTING.md - similar to https://github.com/cucumber/gherkin3/blob/master/ruby/CONTRIBUTING.md#make-a-release

Can you help with this @muhqu ?

**Comment by muhqu** [comment]
I don't know, i think we should not promote the use of `gopkg.in`. Gophers have their very own habits on how to handle dependency management. 

When we start tagging in this [gherkin3](https://github.com/cucumber/gherkin3) repository, we should ensure these tags propagate to the subtree split repositories like [gherkin-go](https://github.com/cucumber/gherkin-go).

Of course, when shipping a v1 there needs to be the awareness that there must go no breaking changes to that major version. Always ensure backward compatibility within major versions.

**Comment by l3pp4rd** [comment]
it would be pleasant if you could follow semver and tag with major version bump when there are backward incompatible changes. It would make it hard if we introduce a package management tool for applications which has one vendor dependency. What relates to gopkg.in, it may be a temporary solution in some situations. Probably, one day, there will be a commonly adapted package manager for **golang**, but for now semver tags would allow to use at least some other options

**Comment by aslakhellesoy** [comment]
@l3pp4rd does this mean [go/CONTRIBUTING.md](https://github.com/cucumber/gherkin/blob/master/go/CONTRIBUTING.md) documents the go release process correctly and we can close this issue?

**Comment by l3pp4rd** [comment]
maybe it should mention in [make release section](https://github.com/cucumber/gherkin/blob/master/CONTRIBUTING.md#make-a-release) to follow [semver](http://semver.org/) version tag standards, if you agree to follow it.

**Comment by aslakhellesoy** [comment]
`CHANGELOG` mentions semver already

**Comment by aslakhellesoy** [comment]
So - can we close this issue now?

**Comment by l3pp4rd** [comment]
in that case, we can close it, my concern was only about semver in general.
