### ISSUE TITLE
Deprecate old nuget packages

### ISSUE THREAD

**Issue by Romfos** [cucumber/gherkin#76]
Hi,

Now we have a lot of old nuget packages, starting from 2011 year.
Now nuget have depreciation feature.
I've propose to do following actions:
1) Mark as depricated all packages before [6.0.0](https://www.nuget.org/packages/Gherkin/6.0.0)
2) Mark as depricated all beta\rc packages (non-release version) and unlist them (they will be hidden on search UI, but still available)

Motivation:
Nuget will have depreciation warning during restore + warning icon in search window in package explorer. 
Because this versions are outdated this is good mechanism ask people to migrate to never and supported versions

Nuget package link: https://www.nuget.org/packages/gherkin/#versions-body-tab

Version | Downloads | Last updated |   |  
-- | -- | -- | -- | --
26.0.1 | 0 | 3 hours ago |   |  
26.0.0 | 0 | 4 hours ago |   |  
25.0.2 | 11,248 | a month ago |   |  
25.0.1 | 1,930 | a month ago |   |  
25.0.0 | 136 | a month ago |   |  
24.1.0 | 10,844 | 2 months ago |   |  
23.0.1 | 122,505 | 9 months ago |   |  
23.0.0 | 2,042 | 9 months ago |   |  
22.0.0 | 181,995 | 23/09/2021 |   |  
20.0.1 | 59,966 | 19/07/2021 |   |  
20.0.0 | 3,564 | 08/07/2021 |   |  
19.0.3 | 7,560,194 | 24/05/2021 |   |  
19.0.2 | 3,909 | 19/05/2021 |   |  
6.0.0 | 14,422,703 | 25/03/2019 |   |  
6.0.0-beta1 | 239,546 | 22/11/2018 |   |  
5.1.0 | 123,796 | 30/05/2018 |   |  
5.0.0 | 260,800 | 13/10/2017 |   |  
4.1.4-rc1 | 1,272 | 04/10/2017 |   |  
4.0.0 | 50,049 | 10/04/2016 |   |  
3.2.0 | 5,589 | 12/01/2016 |   |  
3.1.2 | 9,580 | 03/10/2015 |   |  
3.1.1 | 1,601 | 03/09/2015 |   |  
3.1.0 | 1,787 | 15/08/2015 |   |  
2.12.2 | 2,154 | 12/10/2013 |   |  
2.12.1 | 1,682 | 10/08/2013 |   |  
2.12.0 | 1,523 | 21/04/2013 |   |  
2.11.8 | 1,431 | 09/04/2013 |   |  
2.11.7 | 1,457 | 05/04/2013 |   |  
2.11.6 | 1,499 | 29/01/2013 |   |  
2.11.5 | 1,702 | 14/10/2012 |   |  
2.11.4 | 1,567 | 09/10/2012 |   |  
2.11.3 | 1,638 | 08/10/2012 |   |  
2.11.2 | 1,604 | 17/08/2012 |   |  
2.11.1 | 1,504 | 23/06/2012 |   |  
2.11.0 | 1,545 | 08/06/2012 |   |  
2.10.0 | 1,505 | 07/05/2012 |   |  
2.9.3 | 1,537 | 26/03/2012 |   |  
2.9.2 | 1,599 | 26/03/2012 |   |  
2.9.1 | 1,538 | 16/03/2012 |   |  
2.9.0 | 2,367 | 20/02/2012 |   |  
2.8.0 | 1,489 | 18/02/2012 |   |  
2.7.7 | 2,142 | 08/02/2012 |   |  
2.7.6 | 1,593 | 25/01/2012 |   |  
2.7.5 | 1,552 | 25/01/2012 |   |  
2.7.4 | 1,565 | 20/01/2012 |   |  
2.7.3 | 1,610 | 12/01/2012 |   |  
2.7.2 | 1,564 | 05/01/2012 |   |  
2.7.1 | 1,580 | 10/12/2011 |   |  
2.6.9 | 1,586 | 03/12/2011 |   |  
2.6.8 | 1,598 | 23/11/2011 |   |  
2.6.7 | 1,587 | 22/11/2011 |   |  
2.6.6 | 6,247 | 19/11/2011

**Comment by mpkorstanje** [comment]
This is kinda cool. We didn't know this existed. 

While these releases are old, we don't believe there is anything wrong with these. What would be a good reason for deprecation?

**Comment by Romfos** [comment]
Yea, this is relatively new feature on nuget

Example: 
https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/
https://www.nuget.org/packages/Newtonsoft.Json

You can specify or do not specify exact reason. 
In any case we will provide technical support\bugfix for such old version

Good to hear another opinions :)

**Comment by mpkorstanje** [comment]
We don't provide bug fixes for anything but the latest release anyway. 😄

Nuget is already able inform users their version is old. So 
I don't see much value in a bunch of admin work.
