### ISSUE TITLE
Dependabot config

### ISSUE THREAD

**Issue by mattwynne** [cucumber/gherkin#79]
Trying to configure dependabot to do dependency upgrade PRs for ruby

**Comment by mattwynne** [comment]
So far I've tried https://github.com/cucumber/gherkin/commit/33910b1ef29e08f485b1db4ea039927a621957b7 but it's still creating PRs (see https://github.com/cucumber/gherkin/pull/80) that are too loose.

**Comment by mattwynne** [comment]
The workflow for testing changes to this config seems to be that you have to merge and then revert the PR.

**Comment by mpkorstanje** [comment]
Made Renovate handle it using the workaround from https://github.com/renovatebot/renovate/issues/10616#issuecomment-1364595821****
