### ISSUE TITLE
python: Implement markdown token scanner

### ISSUE THREAD

**Issue by elchupanebrej** [cucumber/gherkin#88]
### 🤔 What's the problem you're trying to solve?

I develop https://pypi.org/project/pytest-bdd-ng/ and try to use as many official tools of gherkin as possible. To have the possibility to execute *.md files I need an appropriate token scanner

**Comment by temyers** [comment]
Already looking at this here: https://github.com/cucumber/gherkin/pull/64

**Comment by mattwynne** [comment]
#4 is a blocker on this

**Comment by mattwynne** [comment]
Closing in favour of #64
